### ISSUE TITLE
Sub-directories are not handled for zip/folder format

### ISSUE THREAD

**Issue by Altazimuth** [team-eternity/eternity#103]
Now that we have uncompressed folder support, sub-folder support is pretty much required due to the automatic sorting nature of OSes, and wad editors. Without it havoc is wreaked on carefully placed structures. Where in zips/wads a marker would suffice, a sub folder is required for organisation here. Provided is an image example of a structure in a pke (zip) that suddenly becomes worthless in uncompressed format. The feature is useful for this reason, and additionally because it's another step towards better compatibility with ZDoom. I'm not saying infinite depth is required, but for certain projects you might have, for example, `sprites/items/health/stimpack` where otherwise the project would appear very messy.
![WadStructure](https://cloud.githubusercontent.com/assets/5298767/18034534/4c11751e-6d37-11e6-9608-1b94bb0ecbbc.png)

For reference, this is what it looks like after decompressing.
![ugh](https://cloud.githubusercontent.com/assets/5298767/18034974/414a9b5e-6d43-11e6-8b6c-cc9f45ef1991.png)

**Comment by Pink-Silver** [comment]
I would like to add that this would be a huge help for organization in team-based or big projects because the nature of large texture packs often calls for a method to keep them split up so that editors, like GZDoom Builder or Doom Builder 2 for example, can list them by category using their folder structure, which helps out being able to sort them by theme.

**Comment by Altazimuth** [comment]
I got it working with minimal code, as long as @ioan-chera and @haleyjd are happy then I'll put it in.

![Hooray](https://i.imgur.com/701VlRb.png)

**Comment by Altazimuth** [comment]
Sorted. Now goes up to a maximum depth of 10 (0-9).
