### ISSUE TITLE
Doom 64 fullscreen HUD layout

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#107]
I was thinking it'd be nice to have the HUD layout from Doom 64 as an option.

**Comment by Blastfrog** [comment]
I made a mockup of how I feel it should be. I took overscan into account (something Doom 64 EX doesn't do).

http://i.imgur.com/0y6cBJx.png

**Comment by ioan-chera** [comment]
Closed because it's an arbitrary request.
