### ISSUE TITLE
Left aligned HUD messages

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#108]
I'm surprised there's no option to place messages in the upper-left corner like traditionally, only Heretic style centered. It'd be nice to have messages in their original place.

**Comment by CapnClever** [comment]
Tested on Heimdal, Win7 64-bit.

Left-aligned HUD messages occur in the legacy, 5:4, and 4:3 video modes, where center-aligned HUD messages occurs in the 3:2, 16:10, 5:3, WSVGA, and 16:9 video modes.

Out of curiosity, I tried some custom options here as well:
- 888x666, which precisely fits a 4:3 aspect ratio, left-aligns the text
- 888x667, slightly taller, left-aligns the text
- 888x665, slightly shorter, center-aligns the text

**Comment by Altazimuth** [comment]
This is pretty silly, and really should be made user-configurable.
Possibly three options for text alignment, "Resolution default" (or just "default"), "Left", and "Center".

**Comment by ioan-chera** [comment]
I love centred messages. Won't "fix" this.

**Comment by Altazimuth** [comment]
The option should be there. I'm gonna go to work on this.
