### ISSUE TITLE
Smooth chainsaw bobbing

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#113]
It would be nice if there was an option to bob all weapon sprites smoothly, even if they don't call WeaponReady every tic.

**Comment by haleyjd** [comment]
Strife VE has a fix for this so I already know how to implement it. Of course it is sync critical so it will have to be stored in demos and transmitted in netgames.

**Comment by ioan-chera** [comment]
This is something that should be done in a mod, not in the main port.
