### ISSUE TITLE
segfault loading a save of tls.wad with v3.40.47 on Mac

### ISSUE THREAD

**Issue by jmtd** [team-eternity/eternity#121]
Using the Bifrost build for Mac, I'm getting a segfault when trying to reload a save of [tls.wad](https://www.doomworld.com/idgames/levels/doom2/Ports/s-u/tls). Nothing useful on the console output. Here's what Apple's crash handler says was the backtrace:

```
Thread 0:: Dispatch queue: com.apple.main-thread
0   eternity                        0x001bdd02 D_Display() + 1922
1   eternity                        0x001d0b9c D_DoomMain() + 53420
2   eternity                        0x00308bb8 -[SDLMain applicationDidFinishLaunching:] + 152
3   com.apple.Foundation            0x935087a2 __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 50
...
```

The save is 

```
-rw-r--r--  1 jon  staff   3.5M 26 Sep 21:34 etersav0.dsg
```

available here https://jmtd.net/tmp/etersav0.zip (300K)

**Comment by Altazimuth** [comment]
At this point, I am unable to test your save as the format has changed. If you ever replicate this issue in the future with a more recent build (you'll need your own git ones as DRDTeam builds aren't working atm) please make sure to attach it here ASAP. I'll make sure to keep an eye out for any save-loading issues I encounter.

**Comment by jmtd** [comment]
I didn't this this a second time when saving TLS (same version of Eternity), so I suggest we just close this issue now.
