### ISSUE TITLE
Incorrect help screens used

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#122]
If playing Doom 1 and a HELP lump is present, it will be used. Likewise, if playing Doom 2 and a HELP1 and/or HELP2 lump is present, those will be used too.

Chocolate Doom only uses the respective game's help lumps.

**Comment by ioan-chera** [comment]
Seems that Eternity's decision was implemented differently, collecting any HELP lumps it can get, even custom lumps.

Are there any released wads which depend on this and look wrong in Eternity?

**Comment by ioan-chera** [comment]
Closing because we didn't get any reply, so it may be irrelevant now.
