### ISSUE TITLE
Crushing polyobjs crush when they're not supposed to

### ISSUE THREAD

**Issue by Altazimuth** [team-eternity/eternity#125]
See example wad. Stand perfectly still and press the switch and you get crushed (unintended behaviour). If you stand so that you are entirely within the sides of the polyobj and you won't get crushed until you hit the wall (intended behaviour). If you grind (or stand stationary) against the wall, parallel to the motion of travel, you will get crushed (unintended behaviour). 

I believe this issue is to do with Polyobj_pushThing, the P_CheckPosition within, and the PIT_CheckLine passed as a parameter by P_CheckPosition to P_BlockLinesIterator.

http://s000.tinyupload.com/index.php?file_id=01243181064353138418 GitHub isn't wanting to upload my attachment properly so here's a link to tinyupload instead.

EDIT: The offending return that causes the damage to happen is the second link, there may be earlier things that allow this to happen though. It's called from the first link.
https://github.com/team-eternity/eternity/blob/master/source/p_maputl.cpp#L687-L688
https://github.com/team-eternity/eternity/blob/master/source/p_map.cpp#L685-L712

**Comment by Altazimuth** [comment]
To simplify, if a polyobj pushes into you with any of its edges then it damages you, as if the edges were razor sharp or something.

**Comment by ioan-chera** [comment]
I've tested this map (https://dl.dropboxusercontent.com/u/5103936/forum-posts/eternity/bugs/polydamageclassic.wad) with the last official Eternity build, and I still see differences from Hexen (and common sense) crush behaviour, causing me to believe it's an older bug to fix here.

**Comment by ioan-chera** [comment]
Fixed
