### ISSUE TITLE
SDL2 support?

### ISSUE THREAD

**Issue by Danfun64** [team-eternity/eternity#130]
There appears to be no evidence that the Eternity Engine is getting ported to SDL2, a move that some ports (PrBoom-Plus, ((G)/(Q))Zdoom, Doomsday) have already made, and one that other ports (Chocolate-Doom/Crispy-Doom, 3DGE, Odamex, Zandronum, Sonic Robo Blast 2) are in the process of being ported to. SDL1.2 is dead, I recommend you move forward (even though it necessarily means abandoning versions of Windows before XP).

**Comment by marrub--** [comment]
I believe Quasar wants to port to SDL2 once Chocolate is done, since it has a nice implementation of that.

**Comment by Altazimuth** [comment]
This is also what I know. Expect progress when Choco is completely done with the migration to SDL2, and when Quasar is free as he has a very tight grip on the HAL code.
