### ISSUE TITLE
Investigate Eternity's problems with ZokumBSP

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#134]
A new node builder has appeared that strongly optimizes the non-editor map features to make bigger maps play in vanilla Doom. Its name is ZokumBSP. 

Unfortunately Eternity, if you don't use -vanilla, as well as many other ports not running in compatibility mode, fail to load such maps properly, by often failing to clip against certain linedefs. With -vanilla it works, which means the problem may be conditioned by demo_version or comp[] flags somewhere where blockmaps are handled.

Doomworld thread: https://www.doomworld.com/vb/source-ports/92468-introducing-zokumbsp/

**Comment by Altazimuth** [comment]
Keeping this open, as the most recent commit should only be a temporary measure.

**Comment by Altazimuth** [comment]
Closed for the moment, though future optimisations may also prove problematic, so re-opening is in the cards later on.
