### ISSUE TITLE
Minor issue with CMakeLists.txt

### ISSUE THREAD

**Issue by fluffymormegil** [team-eternity/eternity#135]
The values of CPACK_PACKAGE_VERSION_MINOR and CPACK_PACKAGE_VERSION_PATCH have apparently not been updated in years, and still result in the Debian packages produced by "cpack -G DEB" being labelled as version 3.37.00.

**Comment by Altazimuth** [comment]
Thanks for bringing this up. I'll make sure we keep an eye out for this in future.
