### ISSUE TITLE
Feature Request: Add automap overlay

### ISSUE THREAD

**Issue by Danfun64** [team-eternity/eternity#139]
It's kind of annoying that while this port is more advanced than Crispy Doom and PrBoom-Plus (and in some ways Odamex) there's a feature that all three of those ports, along with the advanced port ((G)/(Q))ZDoom and its modern derivatives have that Eternity lacks: the option to overlay the automap on actual gameplay, a feature I use frequently. Granted, I'd prefer that you use the Crispy Doom/PrBoom-Plus method of "enable overlay when you press O" rather than the Odamex/((G)/(Q))ZDoom method of "cycle through normal and overlay when you press TAB".

EDIT by printz: checklist.

- [x] Make sure it works correctly when view is changed
- [ ] Make sure it's actually useful for general gameplay to have the tab-tab-tab approach.
- [x] Make sure that the state transition is always correct from none->overlaid->full (so when changing level from overlaid, next time you don't get full as you press tab)

**Comment by ioan-chera** [comment]
I prefer the ZDoom way, personally, as it seems more intuitive from your description. I didn't even know PrBoom+ has an overlaid automap.

Something extra I'm considering: to avoid clutter, areas in other map layers (beyond linked portals) shouldn't appear in the overlaid map, but only in the fullscreen map. This would remind me of Dark Forces, where the displayed map would change when you visit enter layer.

I'll have to see what the other guys and gals think of this.

**Comment by Danfun64** [comment]
IDK, for me it's more intuitive for "turn automap on, turn automap off"...but I digress.

**Comment by ioan-chera** [comment]
IMPORTANT NOTICE: it has to be run after R_RenderPlayerView.
