### ISSUE TITLE
Horizontal and vertical mouse sensitivity extremely inconsistent

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#14]
Vertical mouse movement seems to be a lot more sensitive than horizontal mouse movement. It'd be nice if the having the same sensitivity value on both axes caused them to move the same number of degrees (taking aspect ratio correction into account, of course).

As it is right now, I have to have my horizontal sensitivity a lot higher than the vertical setting just to get it to feel roughly consistent.

**Comment by ioan-chera** [comment]
Seems subjective. Anyway, the vertical sensitivity has good reasons to be set lower than the horizontal one, because looking up and down is done at much smaller angles than turning left and right, especially in a software renderer like Eternity's.
