### ISSUE TITLE
Hexen-style double skies don't work at all

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#141]
It seems that the feature is completely disabled. There is some old code still remaining, which is not currently called, but it's really buggy if actually used, having vertical bars appear above each vertex within the sky area.

**Comment by Altazimuth** [comment]
It's a tough call on what to get working first. A possible plan-of-attack would be to get each sky's scroll speed working, comment that out, then get the transposition of one sky over the other working, then stitching it together with the scrolling.

**Comment by ioan-chera** [comment]
This needs some help from @somtwo  should he return. It involves reusing his super optimized column drawer and modifying it to draw to skies. The disabled code currently in the source code is dysfunctional and buggy.

**Comment by ioan-chera** [comment]
Finally fixed.
