### ISSUE TITLE
Eternity chokes on zero-length EDF lumps

### ISSUE THREAD

**Issue by fluffymormegil** [team-eternity/eternity#148]
If one of the automatically-invoked EDF lumps (e.g. ESTRINGS) in a PWAD has zero length, Eternity fails with the following message:

E_ParseEDFLump: failed to parse EDF lump ESTRINGS (#2213, code -1)

This is understandable, but perhaps not ideal, behaviour.

**Comment by ioan-chera** [comment]
fixed
