### ISSUE TITLE
MIDIPROC compilation failure on paths with spaces

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#149]
It seems the part of the project build setup which processes MIDIPROC.IDL fails parsing spaces in paths.

When building with Visual Studio 2015, I get this:

5>------ Build started: Project: Eternity, Configuration: Debug Win32 ------
5>  Building win32
5>  Microsoft (R) 32b/64b MIDL Compiler Version 8.00.0603
5>  Copyright (c) Microsoft Corporation. All rights reserved.
**5>midl : command line warning MIDL1009: unknown argument ignored "C:\Users\Ioan"
5>midl : command line warning MIDL1009: unknown argument ignored "Chera\Dezvoltare\eternity\midiproc\midiproc.idl"**
5>  Processing Chera\Dezvoltare\eternity\midiproc\
5>  midiproc"
5>c1 : fatal error C1083: Cannot open source file: '**Chera\Dezvoltare\eternity\midiproc**"': No such file or directory
5>midl : command line error MIDL1003: error returned by the C preprocessor (2)
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: The command "../midiproc/genmidiprocWin32.bat
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(123,5): error MSB3073: :VCEnd" exited with code -1.
========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Altazimuth** [comment]
I tried wrapping stuff in quotation marks, but had no luck. I could do with a batch wizard right now, to try and fix this.
