### ISSUE TITLE
EMAPINFO's ability to define non-standard level names has outstripped the rest of the engine's ability to refer to them

### ISSUE THREAD

**Issue by fluffymormegil** [team-eternity/eternity#150]
The EMAPINFO format - according to the Eternity wiki - allows levels to be given non-standard names such as "MYLEVEL", and then referred to using nextlevel / nextsecret. However, as far as I can tell, such levels:

* can't be accessed via the IDCLEVnn cheat, because that cheat can only refer to levels which conform to the standard name for the game being played (either MAPnn or ExMy).
* can't be sensibly referred to by the ACS Teleport_NewMap action, because there is no visible way to define the number of such a level.

**Comment by Altazimuth** [comment]
IDCLEVnn is problematic, and I don't really think thats something that can be solved. If you want to cheat to a map, there is always the console "map mapname", which is more versatile. Teleport_NewMap is a bit hairier. One possible solution would be, if we ever adopt it in future, to allow overloading with ZDoom's arg0str property, but I don't know how clean overloading lines specials would be if implemented in Eternity.

Does ZDoom provide a method to use Teleport_NewMap-like function to go to a map by name, as opposed to number? I can't find one at the moment.

**Comment by fluffymormegil** [comment]
According to [the ZDoom wiki](https://zdoom.org/wiki/MAPINFO/Map_definition), ZDoom allows you to explicitly define the map number of maps whose lumpname does not conform to the expected format for the game being played by specifying the LevelNum property of the map.

ZDoom even lets you redefine the episode structure so that you don't have to use the ExMy format for any of your maps.

**Comment by Altazimuth** [comment]
printz and I were discussing this issue, and we both happened to come up with this idea as a solution (allocation numbers to maps with nonstandard map name). Given this, the basic functionally of specifying a levelnum will likely be added; I am not too sure about the more standard episode structure redefining though.

I don't know when any of us will be able to get to this though; I myself am rather swamped with university work, and only really have time to fix smaller bugs (if I have any time at all to spend on Eternity).
