### ISSUE TITLE
-vanilla is never applied to savegames

### ISSUE THREAD

**Issue by Catoptromancy** [team-eternity/eternity#156]
Using jump key to test if vanilla is active. 
Launch eternity with `-vanilla -warp 01`, jumping will be disabled. 
Save game and exit eternity.
Launch eternity, then loadgame. Jump will be enabled.
Also, `$eternity -vanilla -loadgame 0` also allows jumping.

-vanilla never applies if game is loaded from a save.

**Comment by ioan-chera** [comment]
Fixed. -vanilla is now stored in save games, but still won't persist when starting a new game or warping.
