### ISSUE TITLE
Incorrect portalfloor/portalceiling properties can cause crashes

### ISSUE THREAD

**Issue by Altazimuth** [team-eternity/eternity#164]
See example map, the crash occurs when sectors 27 and 29 have their portalfloor/portalceiling properties incorrectly set to -1/1 instead of -4/4. P_buildPortalMap doesn't get called before Polyobj_movePortals for some reason.

[PortTest_crash.zip](https://github.com/team-eternity/eternity/files/1062028/PortTest_crash.zip)

**Comment by ioan-chera** [comment]
Fixed
