### ISSUE TITLE
STRAIN.WAD demo desyncs

### ISSUE THREAD

**Issue by CapnClever** [team-eternity/eternity#165]
Tested on Heimdal, Win7 64-bit. (Fully edited, read again for more accurate info.)

First you'll have to grab [this UV-Max demo pack](http://doomedsda.us/lmps/collections/stuvmax.zip). Desyncs include:
* st04-237: Around the 44sec mark, there's an imp where it shouldn't be when the player tries to go up the steps.
* st05-154: Player isn't supposed to fire before opening the first door.
* st07-201: 20s in, there's a chaingunner who's supposed to be busy attacking an imp but is facing you instead. Player dies shortly after.
* st11-544: It's most apparent about a minute in, but I think the desync occurs closer to 45s when the player gets caught on a lost soul just after some platforming.
* st14-653: About 8s in there are more imp projectiles than expected. Player dies shortly after.
* st16-610: About 2s in, another instance of "shooting instead of drawing weapon".
* st17-944: Player dies around the 3m mark.

In case you need to know compatibility options (if they matter during playback), I set everything on all pages to "YES". Hopefully that's correct for Doom2 1.9.

One definite bug I've noticed is that EE gives the player 1 bullet at the start of levels, whereas something like Chocolate Doom gives 0 bullets. This is certainly the reason for desyncs in st05 and st16, though it could be related to all of these.

**Comment by Altazimuth** [comment]
Which version of STRAIN are you using? https://www.doomworld.com/idgames/levels/doom2/megawads/strain10, https://www.doomworld.com/idgames/levels/doom2/megawads/strain, or something else?

**Comment by Altazimuth** [comment]
Fixed by https://github.com/team-eternity/eternity/commit/ebf365124cd3c0d9458e0fb3a43786645d72a80e
Thanks for flagging this issue up! Your point about the errant giving of 1 bullet was exactly the information we needed to know where to start looking. Kind of amazing that so much can desync by just that one thing.

**Comment by ioan-chera** [comment]
Is this fixed? If so, shouldn't it be closed?

**Comment by Altazimuth** [comment]
Good point.
