### ISSUE TITLE
Demo camera issues

### ISSUE THREAD

**Issue by CapnClever** [team-eternity/eternity#166]
Tested with Heimdal, Win7 64-bit. A few things, in order of what I would consider priority:

* ~~Turning on walkcam when on the title screen crashes the game.~~ Fixed with https://github.com/team-eternity/eternity/commit/85aa6905dffbab139635ed62e17e7f5d01b14764
* ~~When walkcam is on in windowed mode, the mouse isn't grabbed.~~ Fixed with https://github.com/team-eternity/eternity/commit/9943193e463c9fe7fcf8b5b23bd0186c6ed8341b
* ~~Walkcam always disables automatically when entering a new map; chasecam always disables when restarting Eternity Engine.~~ Fixed with https://github.com/team-eternity/eternity/commit/c2f045ee3e58df4d3d5233bc9aa3af11b10f21b4
* The menu exclusivity between "Walkcam" (WC) and "Chasecam" (CC) is a little wonky. If WC is on and you turn on CC, WC is set to off as expected, but if CC is on and you turn on WC then CC stays on. (If both are on and you turn one off, the other turns off as well.) Maybe have a "Camera Mode" settings with Off/Walk/Chase? ("Walkcam" is a little unintuitive as a name, especially with Chasecam next to it: perhaps "Remote" would do better.)
* You can turn on walkcam and chasecam when not in a demo. It's actually a cool feature for chasecam, but walkcam is awkward considering you move both the player *and* the camera at the same time.
* Chasecam doesn't move through walls. I imagine this is intended out of simplicity, so (as a feature suggestion) it'd be nice to have any solid linedef between chasecam and player be ignored when rendering, at which point the camera can stay the same distance away from the player.
* How does "Chasecam Speed %" work? Feels like it's the speed of snap-to, as it speeds up when farther away from the player. I'm not sure if there's a better name for it if that's the case (Chasecam Snap % seems equally awkward) but it may be worth giving the option name a thought.

**Comment by Altazimuth** [comment]
First point fixed. Can't replicate the second. Looking into the third, but having a hard time figuring out why I can't get the walkcam setting to persist between levels. Fourth needs dealing with, and should be reasonably simple. The fifth could also be relatively simple, if there's a variable that states a demo is currently being played. No clue about the last two.

Will keep you posted.

**Comment by ioan-chera** [comment]
Closing this because the remaining issues are less bugs and more as design issues, and would be better off filed again as individual issues.
