### ISSUE TITLE
Eternity x64 build from DRDTeam crashes with no explanation

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#167]
There's a strange "Eternity-x64-.7z" download on https://devbuilds.drdteam.org/eternity/ which when run will simply output something to CRASHLOG.TXT with an "exception" thrown from "main".

**Comment by Altazimuth** [comment]
I can't get any x64 DRDTeam build to work.

**Comment by Altazimuth** [comment]
OK so this is just a problem when I CMake the sln it crashes on this line:
https://github.com/team-eternity/eternity/blob/master/source/Win32/i_opndir.cpp#L189
