### ISSUE TITLE
Run key to walk with always run

### ISSUE THREAD

**Issue by Gaerzi** [team-eternity/eternity#178]
Copied from [a ZDoom thread](https://forum.zdoom.org/viewtopic.php?f=12&t=59268).

> I apologize if this is the wrong subforum, if so, please move it where appropiate. I don't have a Doomworld account (yet), so I'm curious if any Eternity Engine developers frequent this board. It's just a very small problem I have with this engine. Namely, when always run is on, pressing the run key (for example shift) doesn't make you walk. It works the other way around, though. Btw, every Quake engine except Quakespasm has got that problem too.
>
> Thx in advance :)

**Comment by ioan-chera** [comment]
The feature already exists: it's the runiswalk cvar. I don't know offhand
if it's available in the menu however, and that may warrant a fix.

Same with autorun -- the only non-console way I know is to use something
like capslock to toggle it.

Eternity menus are a bit dense so it may be unobvious where to place these
options.
