### ISSUE TITLE
Enable more compatibility options by default

### ISSUE THREAD

**Issue by pat0gen** [team-eternity/eternity#180]
From what I can tell, the engine currently disables death exits and "ghost" monster by default. These behaviors are abused in very popular custom wads such as scythe.wad and requiem.wad. Correct me if I'm wrong but it seems like enabling the corresponding compatibility options would be better.

**Comment by Altazimuth** [comment]
Ah yeah, bloody comp_zombie. I've run into issues with that before. It's definitely something I'll discuss with Quasar. What other compatibility defaults are causing you grief?

**Comment by pat0gen** [comment]
I'm not really familiar with most of them and I haven't played with Eternity that much yet, so can't really think of anything else right now. However, I do wonder how to set it up properly for boom-compatible maps, since I can't find any easy switch like complevel in prboom or compatmode in zdoom.

**Comment by ioan-chera** [comment]
Fixed. Also restored some other compatibility effects, particularly the "lost souls can get stuck behind walls" (was breaking any maps with caged pain elementals) and the ones related to cheating or mere visual effects.

Still don't know how to address the comp_theights (Doom decoration z-clipping hack fix that preserves vanilla behaviour while giving them consistent actor heights) whenever linked portals are present.
