### ISSUE TITLE
Vsync is always active even when turned off

### ISSUE THREAD

**Issue by pat0gen** [team-eternity/eternity#181]
When I disable vsync, it is still applied, even though use_vsync is set 0 in the config. I can only turn it off through the video driver control panel.
Tested with Eternity-3.42.03a-269-gd0667bb. The system is Windows 7 x64, NVidia GTX 750 Ti, driver v.384.76.

**Comment by Altazimuth** [comment]
Thanks for the bug report, by the way! This would have been really embarrassing if it made its way into the next release. Turns out I was setting swap interval before the GL context was created (bad).

**Comment by pat0gen** [comment]
No problem, glad it helped :D
