### ISSUE TITLE
Demo desync: dvii-21-1609-pw.lmp (-complevel 9)

### ISSUE THREAD

**Issue by DerTodIstEinDandy** [team-eternity/eternity#204]
I'll mirror this report here, just in case: [Deus Vult II pack](https://www.doomworld.com/idgames/levels/doom2/Ports/d-f/dvii-1i) includes demo file dvii-21-1609-pw.lmp. This demo plays fine in prboom-plus -complevel 9, but desyncs for me after a couple minutes  in both 4.00.00-win32 release and Eternity-4.00.00-218-g4ef5d247 devbuild.

**Comment by ioan-chera** [comment]
Fixed. It was caused by the different blockmap algorithm. PrBoom+ still uses the Boom algorithm, and it's justified under -complevel 9.

Unfortunately PrBoom+ also uses it for -complevel 11 instead of MBF's.
