### ISSUE TITLE
Having the game resolution smaller than actual resolution.

### ISSUE THREAD

**Issue by theptoing** [team-eternity/eternity#211]
It does not seem possible to play certain resolutions unblurry in fullscreen mode, such as 320x200.
Maybe some option to map a lower resolution onto a higher one (basically what ports like Choco do), would be nice. Possibly also an option to have individual settings for horizontal and vertical filtering.

**Comment by DerTodIstEinDandy** [comment]
Wait, isn't it already implemented with [fullscreen desktop mode](https://www.doomworld.com/forum/post/1858848)? I set video mode to "640x360fd" and it looks sharp just like crispy/choco. Have to make sure nearest filtering mode is selected in opengl options though ("gl_filter_type 1" in system.cfg).

**Comment by theptoing** [comment]
Yeah, that seems to work indeed. Settings to just filter either horizontal or vertical would be still good though.

**Comment by Altazimuth** [comment]
Resolved some time ago.
