### ISSUE TITLE
Xcode instructions do not work

### ISSUE THREAD

**Issue by linguica** [team-eternity/eternity#233]
Following the instructions for Xcode do not result in a playable build.

Steps to reproduce:

* Install Xcode from scratch
* Clone eternity repository
* Download the 3 SDL development frameworks and place inside /macosx/
* Attempt to built project

Result: fails with messages

> dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: /Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Products/Debug/eternity
  Reason: image not found
Program ended with exit code: 9

> Ld /Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Products/Debug/eternity normal x86_64
    cd /Users/andrewstine/eternity/macosx
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Products/Debug -Lstaticlib -Llibc++ -F/Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Products/Debug -F/Users/andrewstine/eternity/macosx -filelist /Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Intermediates.noindex/EternityEngine.build/Debug/eternity.build/Objects-normal/x86_64/eternity.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Intermediates.noindex/EternityEngine.build/Debug/eternity.build/Objects-normal/x86_64/eternity_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib=libc++ -lz -framework OpenGL -framework SDL2 -framework SDL2_mixer -framework SDL2_net -Xlinker -dependency_info -Xlinker /Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Intermediates.noindex/EternityEngine.build/Debug/eternity.build/Objects-normal/x86_64/eternity_dependency_info.dat -o /Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Products/Debug/eternity

> ld: warning: directory not found for option '-Lstaticlib'

**Comment by linguica** [comment]
If I go into the `/Users/andrewstine/Library/Developer/Xcode/DerivedData/EternityEngine-doijgbghxfhmywescffcdnspcgqp/Build/Products/Debug/` where the executable is placed by XCode, go up one level, then create a "Frameworks" directory to hold the SDL stuff, I can get it to work, but this does not seem like the intended behavior.

**Comment by ioan-chera** [comment]
You know what? I'm just going to automate this.

**Comment by Altazimuth** [comment]
Is this fixed? I saw some XCode commits a bit back.

**Comment by ioan-chera** [comment]
Fixed. SDL shall be downloaded automatically.
