### ISSUE TITLE
[Enhancement] Feature Request: Stats on automap

### ISSUE THREAD

**Issue by AtifArshad1995** [team-eternity/eternity#243]
I like how in ports like prboom+ and zdoom derivatives, u can see the kills, items, secrets stats when viewing automap. Is it possible to have this in Eternity.

( I know there is the alternative/boom fullscreen HUD which shows the stats, but I am not a fan of it and it doesn't work in automap )

**Comment by Altazimuth** [comment]
Done some time ago.
