### ISSUE TITLE
[Heretic] Powered up Firemace does not 1-shot-kill non-boss enemies

### ISSUE THREAD

**Issue by AtifArshad1995** [team-eternity/eternity#250]
Powered up Firemace should 1-shot-kill (deal 10000 damage) anything below IronLich

**Comment by Altazimuth** [comment]
I found the code in Chocolate Heretic responsible for this behaviour, in P_DamageMobj. It does a switch on inflictor->type.
```c
            case MT_MACEFX4:   // Death ball
                if ((target->flags2 & MF2_BOSS) || target->type == MT_HEAD)
                {               // Don't allow cheap boss kills
                    break;
                }
                else if (target->player)
                {               // Player specific checks
                    if (target->player->powers[pw_invulnerability])
                    {           // Can't hurt invulnerable players
                        break;
                    }
                    if (P_AutoUseChaosDevice(target->player))
                    {           // Player was saved using chaos device
                        return;
                    }
                }
                damage = 10000; // Something's gonna die
                break;
```

**Comment by Gaerzi** [comment]
For what it's worth, in ZDoom, the behavior was generalized with the creation of a DONTSQUASH flag for the Iron Lich. So the "cheap boss kill" check is done by looking for the BOSS flag or the DONTSQUASH flag.

**Comment by AtifArshad1995** [comment]
I think the IronLich is a special case because I personally recall (but i couldnt find any evidence about this) that in version 1.0, powered firemace could even 1-shot IronLich. But dev probably decided to change this in later version.

Also take a read at this for some info:
https://doomwiki.org/wiki/Firemace

According to this, players can be killed by it even in invulnerability mode. And Chaos Device, while saves the player from death, player still losses about half of his health.

**Comment by Altazimuth** [comment]
Ah, well the DONTSQUASH is nice, but the more out there behaviour (chaos device usage) has me scratching my head on how to generalise. Honestly this might be a "Wait for Aeon" situation.

**Comment by Altazimuth** [comment]
Doesn't have to be but I'm not comfortable with how Heretic achieves it, especially when I couldn't find any other hacks in EE's P_DamageMobj.

**Comment by Gaerzi** [comment]
I see. In ZDoom this kind of hacks were exported to a virtual class method DoSpecialDamage function, so the base Actor::DoSpecialDamage does nothing special (just handles godmode there) and the weird hacks can be kept for the override in classes that need them. (There's also its counterpart TakeSpecialDamage.) P_DamageMobj then calls these SpecialDamage functions.

**Comment by Altazimuth** [comment]
I noticed that when I was looking into how ZDoom did it. It's part of why I feel Aeon would be a good fit, since functionality similar to DoSpecialDamage would need to be delegated to Aeon (as is evident by its delegation to ZScript in ZDoom). Aeon (angelscript-branch) is on halt at the moment whilst I figure out how to deal with bloody portal awareness.

**Comment by Altazimuth** [comment]
Turns out we already have a precedent for this. It's called dmgspecial and it's already a thing for the maulotaur and whirlwind.
