### ISSUE TITLE
Reported: 1-pixel noise on midtextures at the beginning of columns

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#267]
A level designer reported some undesired 1-pixel noise at the top of midtexture contiguous columns, similar to the older bug reported by Blastfrog but for the bottoms. Their map has a modified PLAYPAL where index zero is not black, making it easily visible.

Seen when getting really close.

**Comment by Altazimuth** [comment]
Is this potentially due to a failure in assignment of GameModeInfo->blackIndex, or perhaps just somewhere where 0 is used instead of GameModeInfo->blackIndex? Hopefully it's that simple an error.

**Comment by haleyjd** [comment]
It's round off error. The conversion of fixed point scaled texture coordinates to actual pixels can pick up the pixel before (or after) a column, which is why Doom's patch_t format had padding bytes there. This is kind of a tough problem to solve with the textures having been converted to linear buffers.

**Comment by haleyjd** [comment]
PS it was the "after" byte case which previously caused segmentation violations on BSD in MAP01 of No Rest for the Living. If the overread happened on the very last patch in a texture, it would go one past the end of the allocated buffer. This was "solved" by adding padding to the texture buffers, though, the rendering is still likewise incorrect.

**Comment by ioan-chera** [comment]
I fixed the after-byte by copying the colour of the last real texel. I can't believe I didn't see the same effect occurring _before_ the column.

**Comment by ioan-chera** [comment]
done
