### ISSUE TITLE
Eviternity's Demo Loop does not play

### ISSUE THREAD

**Issue by AtifArshad1995** [team-eternity/eternity#284]
Eviternity's demo loop (which are complevel 11 demos as stated by author) does not play in Eternity (Tested using Feb 11 build) but plays fine in PrBoom+.

But in other wads, complevel 11 demos play in Eternity. Valiant is an example of this.

**Comment by ioan-chera** [comment]
The actual demos aren't for MBF (-complevel 11) however. They advertise their version as 214 which is way past 203 which is required for MBF demos. This is why Eternity skips them.
