### ISSUE TITLE
Make jumping a playerclass property and also a compatibility choice

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#286]
Right now jumping is enabled by default everywhere, which is wrong for the vast majority of Doom wads, which are for Doom and PrBoom+. Even the most Eternity maps released so far are designed without jumping.

So make it opt-in by controlling it from two points:

1. Add a jumpheight playerclass property, which controls the up jumping speed. Doomguy and Corvus will have 0 (won't jump)
2. Add a comp_jump option in the compatibility menu to let player enable jumping in any other Doom map, just like it is now. This shall be useful to salvage any existing maps meant for jumping. It will override any jumpheight of 0 to 10.

Also, remove comp_aircontrol. Its only purpose is to make jumping usable. Instead, whenever the player can jump, enable this degree of air control. Other kinds of air control, such as the one set from EMAPINFO, will always work however, regardless of this flag.

Make sure not to error out if a mod has comp_aircontrol in OPTIONS.

**Comment by Altazimuth** [comment]
I've wanted the first of these for a while. I can try sort that out.
As for 2, don't we also have an EMAPINFO property, and don't we disable it during demos as well? Shouldn't be hard to gate off.

**Comment by Altazimuth** [comment]
Jump speed has been made a playerclass property. The default is 8.0. https://github.com/team-eternity/eternity/commit/eaec62594e450e7ba4f5a8a2d0d91d9f63ef9a47

**Comment by Altazimuth** [comment]
Jump speed has been made a playerclass property. The default is 8.0. https://github.com/team-eternity/eternity/commit/eaec62594e450e7ba4f5a8a2d0d91d9f63ef9a47

**Comment by ioan-chera** [comment]
Fixed
