### ISSUE TITLE
No weapon switching when powered gauntlets expire

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#311]
Powered gauntlets should visibly switch to regular gauntlets when the Tome of Power effect expires. Right now they just change seamlessly, which is wrong.

**Comment by Altazimuth** [comment]
It's "wrong", but it the behaviour nevessarily worse? If it switches seamlessly to powered gauntless then why shouldn't it seamlessly switch from them? I was pretty happy with how smooth the transition felt.

**Comment by ioan-chera** [comment]
Because it shouldn't. That's how it was defined.

**Comment by Altazimuth** [comment]
Well then put in a weapon flag that makes the transition crappy or something. It's not "defined" that way so much as they didn't bother to code in the smooth transition. They put in the minimum effort.

**Comment by ioan-chera** [comment]
If something during development accidentally ends up in the game and it's not game breaking and the developers don't mind and don't try to fix it after several months of updates, then it's by design. If you want something different, setup a gameplay mod for frequent use.

**Comment by Altazimuth** [comment]
**Well then put in a weapon flag that makes the transition crappy or something.**

**Comment by Altazimuth** [comment]
Hell, put in a weapon flag that makes the transition smooth if you think more people will want Heretic-style A_Lower calls.

**Comment by ioan-chera** [comment]
Code in Chocolate Heretic which handles this case is in `P_PlayerThink` in:
```
    if (player->powers[pw_weaponlevel2])
    {
        if (!--player->powers[pw_weaponlevel2])
        {
            if ((player->readyweapon == wp_phoenixrod)
                && (player->psprites[ps_weapon].state
                    != &states[S_PHOENIXREADY])
                && (player->psprites[ps_weapon].state
                    != &states[S_PHOENIXUP]))
            {
                P_SetPsprite(player, ps_weapon, S_PHOENIXREADY);
                player->ammo[am_phoenixrod] -= USE_PHRD_AMMO_2;
                player->refire = 0;
            }
            else if ((player->readyweapon == wp_gauntlets)
                     || (player->readyweapon == wp_staff))
            {
                player->pendingweapon = player->readyweapon;
            }
            BorderTopRefresh = true;
        }
    }
```
Need to put something with a flag in the equivalent place in Eternity.

**Comment by ioan-chera** [comment]
Fixed by adding a new weapon flag: DEPOWERSWITCH
