### ISSUE TITLE
Rendering glitch?

### ISSUE THREAD

**Issue by AtifArshad1995** [team-eternity/eternity#317]
I have noticed a rendering glitch on Eviternity's Map26 using latest drdteam build (29 June build). The screenshot shows what I am talking about:

![New Image](https://user-images.githubusercontent.com/43236181/60795288-d4d51480-a184-11e9-8f81-89e76d281f4f.jpg)
 
This glitch does not occur on the official Völuspá release.

**Comment by ioan-chera** [comment]
Fixed. Unfortunately we may be losing an attempted optimization by fixing this; we may see later how to restore that optimization without impacting this kind of rendering.
