### ISSUE TITLE
Maps potentially running too slowly on Eternity

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#322]
According to this Doomworld post (https://www.doomworld.com/forum/post/2020476), a map called Frozen Time seems to run notoriously slow on Eternity. We need to check whether it's a bug or a limit of software renderer's capabilities.

**Comment by Altazimuth** [comment]
"It requires an OpenGL port with support for ZDoom extended nodes, hi-res textures and tall patches."
I mean hopefully it's resolvable but we don't even have hi-res textures, and this is explicitly targeted at GL ports. Making mods targeted intentionally at ports that aren't Eternity work in it isn't anything I ever have any plan to directly tackle. If it happens as a result of work motivated by something else then sure, that's nice, but Eternity doesn't need to be a one-stop shop for every single mod.

**Comment by ioan-chera** [comment]
Closed because the mod requires features which aren't in Eternity. When Eternity aims to run such mods, this will become a valid thing.
