### ISSUE TITLE
Computer area map shouldn't be accepted the second time

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#327]
In Eternity currently the computer area map can be picked up multiple times, when it should only be usable once per map per player.

**Comment by Altazimuth** [comment]
Sounds like a mistake with the EDF or logic of dealing w/ EDF. I'll have to look at this one myself.

**Comment by Gaerzi** [comment]
Plutonia MAP28 has two automaps right at the entrance.
