### ISSUE TITLE
Problem with interpolated sectors ruining moving geometry illusions.

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#333]
https://www.doomworld.com/forum/topic/110185-eternity-uncapped-framerate-issue/

Apparently it's because of sector interpolation that any attempt to move fake geometry by successive instant sector movement will look wrong.

**Comment by ioan-chera** [comment]
done

**Comment by Gaerzi** [comment]
> 
> 
> done

You know, if you write [things like "Fixes #333" in your commit message](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords), it'll close the issue automatically and add a link back from the issue to the closing commit.
