### ISSUE TITLE
[Bug] Warping fails if no map is specified

### ISSUE THREAD

**Issue by sinisterseed** [team-eternity/eternity#340]
Apparently warping fails if no map is specified when the -warp parameter is used.

I tried this recently with NERVE.WAD (**-iwad doom2.wad -file nerve.wad -warp -skill 4 -vanilla**). If no level is specified (ex: -warp 01), warping fails and the console reports that "-skill" is an invalid map - looks like it doesn't jump to the parameter following -warp.

In PrBoom+ it works as intended by starting on the very first map of the WAD, whereas in Eternity the game launches but errors out immediately.

**Comment by ioan-chera** [comment]
Not a bug. You should remove the `-warp` parameter, because just having `-skill` set is enough to hint Eternity to start a new map.
