### ISSUE TITLE
Add DECORATE lump support

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#344]
It would be useful to have DECORATE lump support, at least with the features currently supported by Eternity. This will help supporting some of the ZDoom gameplay mods such as Realm667 resources, without the author or third-party user having to write EDF equivalents. Obviously, Eternity will still be centred on EDF, but DECORATE will act as an alias language, similar to other instances already in, such as ANIMDEFS vs. EDF switch/animation.

**Comment by Altazimuth** [comment]
Non on on o no no nono no onno no nono no nono no no no no no non oonoonon oooooon nooooooooooo good heavens no.

**Comment by ioan-chera** [comment]
Could you elaborate why, please?

Let me think of potential problems. One of them would be the challenge to add new equivalent stuff to DECORATE (as popular demand implies) as we add new stuff to EDF which may be missing from GZDoom.

**Comment by Gaerzi** [comment]
Might be interesting to note that k8vavoom has (partial) DECORATE support, and DelphiDoom's ACTORDEF lump is essentially another subset of DECORATE with a different lump name.

It might be worth resurrecting the old "DECOLITE" idea.

**Comment by Altazimuth** [comment]
We're not going to be able to support DECORATE at all. EE just isn't architecturally good for it. Additionally we'd have to implement a parser for it, which is a pain, and I just don't think it's worth the technical debt that would be around forever, as well as the time it would take to implement. EE isn't GZDoom.
We don't need to eat featuresets from other ports just to try support WADs that aren't targeted at us.
