### ISSUE TITLE
Implement Heretic fullscreen HUD

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#345]
The Heretic fullscreen HUD should have at least the following items:

1. health
2. current inventory item
3. inventory selector
4. currently active power-up (e.g. the tome of power).

As it is now, Eternity has these HUDs:

1. the old BOOM style, with small numbers and letters, which can be arranged on one, two or three corners.
2. a modern Eternity reskin, with a bit more icons but otherwise similarly laid out
3. an graphical HUD with large numbers and armour/health/ammo icons, and without all the level stat info.

Right now in Heretic both 1 and 2 work, but they lack inventory and powerup information (precisely what Heretic added over DOOM). Currently 3 isn't implemented at all in Heretic. Keep in mind that vanilla Heretic has a fullscreen HUD which turns out to be similar to Eternity's DOOM modern HUD. So the suggested steps are:

1. Implement the graphical (iconic) HUD in Eternity Heretic. Make it have at least everything from vanilla Heretic. Possibly add other stuff which is available in Eternity DOOM right now.
2. Improve the BOOM and Eternity modern HUDs to also show the inventory and powerup state.

**Comment by ioan-chera** [comment]
Added health and current power-up display in the fullscreen graphical HUD. Still need:
1. inventory
2. all these things in the BOOM and modern HUDs.

**Comment by Altazimuth** [comment]
I fear cramming inventory into the BOOM and modern HUD without it looking like complete rubbish is not a particularly feasible thing, but should definitely be tried.

**Comment by ioan-chera** [comment]
Here's a screenshot of how it looks in fullscreen. If it's widescreen, the extra space allows for more items to be visible. 
![etrn191](https://user-images.githubusercontent.com/3496907/74124135-f47c6180-4bd9-11ea-9be4-b3703e479dfb.png)
However, I'm not happy yet. I need to implement it as an independent widget which should appear in all Heretic cases where we're fullscreen. Right now it's just part of the graphical HUD in Heretic.

**Comment by ioan-chera** [comment]
Closed, except that the graphical HUD may use some improvement
