### ISSUE TITLE
Add support for the TINTTAB lump for GHOST monsters

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#347]
Heretic has the TINTTAB lump to specify the ghost monster translucency. It seems to be formatted like the BOOM translucency map lumps. Eternity however hard-codes the ghost monster translucency, but needs to be modified to also support the TINTTAB lump if it exists.

Heretic uses the same lump for the HUD font shadow effects. It's debatable whether that's worth supporting too.

**Comment by Altazimuth** [comment]
How many custom TINTTABs are out in the wild? I'd consider this fairly low-prio, but a worthwhile endeavour to do at least some of that stuff. The issue is if it doesn't jive w/ current translucency code.

**Comment by ioan-chera** [comment]
Looks to me just like the BOOM tranmap, so it's easy to support. I also verified that no transposition is involved.
