### ISSUE TITLE
Heretic weapons make no sound when picked up staying

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#348]

**Comment by Altazimuth** [comment]
Please to clarify what the heck this means.

**Comment by ioan-chera** [comment]
When playing -deathmatch (for example), the weapons stay when picked up. The same can be done by fiddling with dmflags. Right now in Eternity Heretic they make no hahaha sound when picked up in this mode (this reminds me of the funny way staying keys act in vanilla DOOM as well and got fixed in EE by you).

**Comment by ioan-chera** [comment]
Fixed
