### ISSUE TITLE
Heretic automap background overlaps statusbar background

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#349]

**Comment by Altazimuth** [comment]
Could you please provide an image demonstrating this issue?

**Comment by ioan-chera** [comment]
![etrn04](https://user-images.githubusercontent.com/3496907/75092820-5c408e00-5584-11ea-90ed-809a67ec7aef.png)

**Comment by Altazimuth** [comment]
That's new...

**Comment by ioan-chera** [comment]
Fixed
