### ISSUE TITLE
Heretic ahead projectiles are not shifted vertically the same as angled ones

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#356]
How to see it: look all the way up and fire the crossbow. In vanilla Heretic the bolts are at the same plane. In Eternity due to an inconsistency the angled ones are shifted vertically.

**Comment by Altazimuth** [comment]
The Heretic spawn missile angle function could probably do with using the same slope logic as the regular spawn missile function in that case.

**Comment by ioan-chera** [comment]
Actually it's not the slope itself which is set wrongly, but the Z of the spawn origin, which in Heretic is also influenced by the pitch. It's possible that the straight ahead projectile does not add the pitch into the Z, so that case needs to be handled.

**Comment by Altazimuth** [comment]
I'd say it's more worthwhile to just not add pitch to z. We don't need another missile spawn function variant; the Heretic one is enough of a pain in terms of cleanliness as-is.

**Comment by ioan-chera** [comment]
I'd say we need to be accurate. I think it can be parameterized in the function without adding a new one with duplicate code.

**Comment by Altazimuth** [comment]
I'd be reticent to add any bool params. C++'s lack of named parameters mean that calls look really confusing at a glance.

**Comment by ioan-chera** [comment]
Yeah, I dislike bools too, but if it gets hairy we can try enums and even structs.

**Comment by ioan-chera** [comment]
Done, but it turns out the small arrows were off-defined, hence the apparent vertical displacement.
