### ISSUE TITLE
Demo desync in 100lineN.wad

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#369]
Demo is from DSDA. Name is 100lineN-11-656-TOD-prplus2513.lmp

Download from: http://doomedsda.us/wad2140.html

Actual demo is in https://github.com/ioan-chera/EternityDemoTest/blob/master/100linen/100lineN-11-656-TOD-prplus2513.lmp

**Comment by Altazimuth** [comment]
Oof. This a long-standing desync, or a more recent one?

**Comment by ioan-chera** [comment]
Recent: I found commit 9790de13a3672bec0013d37b6b9d391dd6ab4c76 to be the one which caused it.

**Comment by Altazimuth** [comment]
That is surprising. Wait... I'll take a look at this.
