### ISSUE TITLE
Demo desync in Hell Revealed 30hr_op.lmp

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#371]
The demo from DoomedSDA (also see my EternityDemoTest to find the file) fails in Eternity at level 3 (the Dumpster), but works on PrBoom+.

Got to test as far back as 3.39.20 and it still desyncs. Didn't test older versions yet.

NOTE FROM USER ON CHAT: @printz Here is the latest unofficial Eternity-DOS build: https://www.vogons.org/viewtopic.php?p=590945#p590945

**Comment by Altazimuth** [comment]
It goes back as far as 3.39.20? Yikes that's almost a decade ago.

**Comment by ioan-chera** [comment]
Version 3.37.00 desyncs even worse, so there's no point looking in earlier Eternity versions

**Comment by Altazimuth** [comment]
Guess we need to find just where the desync starts happening. This sort of demo bug is the worst to try fix. How are we going to figure that out though? We'd need some sort of debug output from PRBoom+ that matches up w/ output from EE too, so they can be diffed against each other.

**Comment by ioan-chera** [comment]
Eternity versions 3.37.00 and earlier desync the same way as MBF, which is even worse than now. But BOOM 2.02 runs it fine.

What I can do is log the P_Random calls and the mobj positions. Ultimately I'll be able to find which function calls are missed. I also need to check if the blockmap didn't unintentionally get corrected (shouldn't be the case however, otherwise all HR maps 3 would desync).

**Comment by ioan-chera** [comment]
Fixed
