### ISSUE TITLE
Berserk doesn't autoswitch when redefining weapons

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#372]
Just added this here: https://www.doomworld.com/forum/topic/112615-redefined-weapons-with-edf-now-berserk-no-longer-autoswitches/ to mark it down.

Marked a bug to stand out until we figure out the real situation (whether it's a bug, an unintuitive EDF behaviour or a mistake in user's EDF file).

**Comment by Altazimuth** [comment]
The berserk directly references the Fist weapon. If you don't have that exact weapon then you're not gonna get the weapon. I implemented some new stuff to make the scenario that birthed this issue more easily resolveable.
