### ISSUE TITLE
Chainsaw replacements still make chainsaw sounds

### ISSUE THREAD

**Issue by maxmanium** [team-eternity/eternity#376]
See: infinite BFG in sf2011.wad, sf2012.wad, sf3.wad, etc.

**Comment by Altazimuth** [comment]
Probably something I broke in trying to generalise "upsound" behaviour. I'll take a look into this.

**Comment by Altazimuth** [comment]
OK so I'll need to stew on this. There's no easy fix for this, seemingly. Might need a hack based on if a dehacked modifies the ready state for the chainsaw in particular.

**Comment by maxmanium** [comment]
Yeah, I mean the idling sound (which is also sped up for some reason).

**Comment by Altazimuth** [comment]
Sped up since there's only the single readystate, the chainsaw isn't constantly iterating through the single state unlike the infiammo BFG.
