### ISSUE TITLE
Add support for the MacBook Touchbar

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#405]
This may be interesting to  implement in DOOM. However, I have no such MacBook with me. I can only use the simulator.

**Comment by Altazimuth** [comment]
To what end? What possibly benefits could outweigh having to have some custom Swift or ObjC or whatever nonsense tied up with the EE code? I thought everybody hated the thing anyway. It's not typist-friendly, and it's more for GUI-centric people.
Additionally it brings to mind Wii U games or DS games where you'd have to suddenly switch from normal controls to using the touchscreen, if there was any input via it. That stuff was horrible.

**Comment by ioan-chera** [comment]
I'm not a typical user of this feature, since my MacBook Pro is too old. However I find it impressive, by looking at the simulator. For example Xcode gives me one-tap shortcuts for "Refactor" or "Jump to Implementation".

Also, if you use a MacBook, you'll see that the F-keys are by default statically linked to the brightness, multimedia and volume controls. You have to hold the Fn key to obtain the classic F-key functionality. This can be reversed in the system settings if you want the F-keys by default. Anyway, the Touchbar offers the same interface if you hold Fn. If you don't hold Fn, it acts as an evolution of the static brightness/multimedia/volume controls, allowing you to do much more than that, depending on current context. This gives me freedom to add something DOOM-like while running Eternity. Or even let user customize it.

As for sticking Objective-C code to EE, that won't be a problem outside of macOS.

The sad thing is that I might skip this entirely and close the issue if the next MacBook Pro ditches this feature.

**Comment by ioan-chera** [comment]
Sadly the masses terminated this idea.
