### ISSUE TITLE
Remove the Xcode project and rely on CMake to produce one

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#409]
It would be best to use CMakeLists.txt for both Linux and macOS development (as it can just generate an Xcode project if desired). This would also ensure that the CMake scripts are actively maintained without needing to have someone oversee Linux development.

This would have the benefit of keeping Eternity development available (as I'd just be able to use Makefile and Visual Studio Code) during the long hours when Xcode updates.

- [x] Setup the Eternity Engine program
- [x] Check that cleaning the Xcode project works
(NOTE: apparently it's not possible to fix this: https://stackoverflow.com/a/55098588/11738219)
- [x] Check that it's safe to strip framework headers from paths with spaces
- [x] Update the warnings and errors to be almost the same as the pre-build project.
- [x] Setup the Eternity-Launch program
- [x] Check that we can get a signed Eternity-Launch program
- [ ] Make sure building from Makefile is possible at least for the main game
- [x] Update versioning.txt
- [x] Delete old xcodeproj bundles
- [ ] Send PR to devbuilds to build the CMake way
- [x] Update the Readme on macOS building

**Comment by Altazimuth** [comment]
I think this is a quite worthwhile effort. Moving towards CMake for everything could be greatly beneficial. I know Quasar wanted to keep the organisation for VS projects, which is possible apparently.
I do want to do a fairly large amount of rejigging to the CMake files since they're old and ugly.

**Comment by ioan-chera** [comment]
From my experience I find the CMake-generated IDE projects kinda ugly, so I'm not gonna force the removal of the VCXPROJ, but I can live with an autogenerated Xcodeproj on my macOS side. Having one common CMakeLists.txt set would also help prevent IDE project desynchronization (like myself forgetting to add new source files in the VCXPROJ), though of course testing on all platforms is always recommended even if we do move to CMake (though it can be tedious…)

**Comment by ioan-chera** [comment]
Forget it. I'm happy with Xcode.

**Comment by ioan-chera** [comment]
Revive this because it's becoming important for cross-platform integrity.
