### ISSUE TITLE
Heretic: remove the swamp sound when stepping on acid

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#410]
Under Heretic, unlike Hexen, there's no sound when stepping on swamp/slime. The Eternity terrain type needs to be modified not to make that Hexen sound.

**Comment by Altazimuth** [comment]
Does Heretic use its own terrain type in the heretic folder, or does it use the base EE stock one?

**Comment by ioan-chera** [comment]
Done. It uses the base one. It happens that all terrain is in the base folder and it's just there separated in conditional directives. I've added a splashdelta just in Heretic to remove the sound.
