### ISSUE TITLE
Problem with linedef special 30

### ISSUE THREAD

**Issue by JoBergeron** [team-eternity/eternity#413]
In Memento Mori 2 map25, you walk over a linedef special 30 and it's supposed to raise a pillar to a certain height. On Eternity, it raises the tagged floor higher than it's supposed to thus blocking progression.

![etrn01](https://user-images.githubusercontent.com/1339414/78593247-53dea280-7814-11ea-9d4d-361ef7cbabde.png)

this central pillar is only supposed to raise as high as in the next screenshot taken in gzdoom

![Screenshot_Doom_20200406_144025](https://user-images.githubusercontent.com/1339414/78593424-9bfdc500-7814-11ea-8141-4c03ce473b7c.png)

**Comment by ioan-chera** [comment]
Unfortunately this is not a bug, but a feature inherited from Boom or MBF. It's the `Use exactly Doom's linedef trigger model` compatibility setting which you have set to NO (which is the default set in Eternity). It doesn't just affect special 30, but a lost of stuff going on in sector movement. Unfortunately some mods (which includes ALL vanilla Doom maps) may depend on it being set to YES, while the Boom specific ones (not necessarily all) may depend on it being set to NO.
