### ISSUE TITLE
Wrong message for super shotgun pickup

### ISSUE THREAD

**Issue by maxmanium** [team-eternity/eternity#416]
![etrn00](https://user-images.githubusercontent.com/58398531/79051808-e78ae700-7bf7-11ea-81fb-2de059f5b2aa.png)
![etrn01](https://user-images.githubusercontent.com/58398531/79051809-e954aa80-7bf7-11ea-8695-aceef59517db.png)

**Comment by Altazimuth** [comment]
Are you on the latest DRDTeam build? I can't replicate this.

**Comment by maxmanium** [comment]
Lol, whoops, I forgot I hadn't updated it. Not sure when this bug popped up but it's fixed now. It's from my own map, but whenever the bug was present it happened with the stock IWADs too.

**Comment by Altazimuth** [comment]
All good. No worries. Apparently printz fixed it on the 22nd of March.
