### ISSUE TITLE
Linux midi volume very low

### ISSUE THREAD

**Issue by JoBergeron** [team-eternity/eternity#430]
Even if both volume bars are maxed our for music and game sounds, the music volume is extremely low in the game. Am I doing anything wrong? Anyone else getting this issue?

**Comment by Altazimuth** [comment]
I hadn't experienced this when I used EE on Linux when I managed to get MIDI working with the SDL_SOUNDFONTS envvar appropriately. More info on your distro and such would be appreciated, please.

**Comment by JoBergeron** [comment]
Running on the latest stable release of ElementaryOS. I've configured timidity to run a custom soundfont. I did not set a SDL_SOUNDFONTS envvar. Is there documentation on that so I can try it out?

**Comment by Altazimuth** [comment]
It's really poorly documented, because of course it is. Also it's not TiMidity++ that SDL_Mixer uses, but Fluidsynth. Here's documentation of SDL_SOUNDFONTS on the Arch wiki but it's handy for all distros. [](https://wiki.archlinux.org/index.php/FluidSynth#SDL_Mixer)

**Comment by JoBergeron** [comment]
I'll check it out later today and report back. Thank you!

**Comment by JoBergeron** [comment]
I've configured the environment variable and still the midi sound level is very low. I've even maxed out the gain settings from the equalizer. It makes it sound a lot louder but not enough. I'm very confused with all this.

**Comment by Altazimuth** [comment]
That's really bizarre. I've had MIDI for EE working out of the box for Debian before, and have also made it work w/o such issues for Ubuntu, Linux Mint, Arch, and Void Linux. Do oldish versions of PRBoom+ have the same problem when using SDL_mixer's MIDI? Additionally, what about when you use libADLMIDI in EE?

**Comment by JoBergeron** [comment]
It turns out I was using libadlmidi all along. 

I installed FluidSynth (I'm sort of newish to Linux and it wasn't installed) and now everything seems to work. However the music that plays at the titlepic is now sort very loud. Everything else seems to work fine though.

The problem seemed to be on my end, my apologies. Thanks for trying to walk me through it though :)
