### ISSUE TITLE
Polyobjects may flicker depending on where you look at them from

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#44]
There seems to be a very serious problem in Eternity with polyobjects, where they start flickering arbitrarily if you look at them from the wrong positions. It doesn't seem to be easily controlled and contained by the map author.

**Comment by haleyjd** [comment]
I believe this is due to the lack of node bounding box expansion. This was implemented in ZDoom when it *ahem* borrowed the dynaseg approach, but the implementation was not done in a way that works with Eternity's node recursion so I could not directly adapt it.

**Comment by ioan-chera** [comment]
fixed
