### ISSUE TITLE
Implement slope collision

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#45]
This is somewhat complex, because special behaviour needs to be done when descending slopes, to prevent trembling and sliding.

Use *SLOPE_TODO* wherever we have stuff to implement but don't know / cannot currently...

TO DO
- [x] Doors highest nearest ceilings to be fully slope aware
- [x] Same with all other similar types
- [x] ACS `GetSectorFloorZ` and `GetSectorCeilingZ`
- [x] Automap: display slope edges correctly, not according to horizontal surface heights.
- [x] Automap HUD z coordinate
- [x] `P_GetFloorHeight`, `P_GetCeilingHeight`: replace floorheight and ceilingheight with these. Have x/y as parameters.
- [x] `P_SetFloorHeight`, `P_SetCeilingHeight`: Move slopes with the sector surfaces (on master they render at the same plane all the time)
- [x] `EV_DoCeiling`: refer to proper slopes when limiting ceiling movement.
- [ ] Vertex slopes (editor support)
- [x] `A_ThingSummon`, `A_PainShootSkull`
- [x] D'sparil spawning height checking needs to check against a collision model
- [x] `E_HitWater`
- [x] Heretic teleport glitter spawning
- [x] ACS SetActorPosition: proper floor Z
- [x] `CAM_` portal aware traces partially done, but sector height calculation is incorrect! Needs fixing.
- [x] `E_GetThingFloorType`: proper floor Z
- [x] `E_HitFloor`: proper floor Z
- [x] `EV_DoCeiling` neighbouring sector floor or ceiling
- [x] `EV_DoDoor`
- [x] `EV_DoElevator` neighbouring sector floor and ceiling
- [x] `EV_DoFloor`, `EV_DoChange`: finding neighbouring sector floor
- [x] `EV_DoParamFloor`, `EV_DoParamCeiling`, `EV_DoGenLiftByParameters`, `EV_DoParamStairs`, `EV_DoParamCrusher`, `EV_DoPlat`, `EV_DoParamPlat`, `EV_DoParamDoor`
- [x] `EV_PillarBuild`
- [x] `EV_PillarOpen`
- [x] `EV_SilentLineTeleport`
- [x] `FrictionThinker::Think`
- [x] `G_CheckSpot`: telefog proper floor Z
- [x] Game saving (are slopes serialized? They're static on master.)
- [x] `Mobj::Think` waterstate
- [x] `P_AdjustFloorClip`
- [x] `P_CheckFPortalState`, `P_CheckCPortalState`
- [x] `P_CrossSubsector`, `P_CheckSight` (p_sight)
- [x] `P_DripEffect`
- [x] `P_ExplodeMissile`
- [x] `P_ExtremeSectorAtPoint`
- [x] `P_Find...Surrounding`, `P_FindModelFloorSector`, `P_FindModelCeilingSector` (for sector movement)
- [ ] `P_FloorPortalZ`, `P_CeilingPortalZ`
- [x] `P_GetChasecamTarget`
- [x] `P_GetFriction`, `P_TeleportMove`, `P_CheckPosition`, `P_CheckPosition3D`, `P_CheckPositionExt`, `PIT_ApplyTorque`, `P_TryMove`
- [x] `P_HereticCurrent`
- [x] `P_LineOpening`, `P_getLineHeights`, `P_blockingLineDifferentLevel`, `PIT_CheckLine3D`
- [x] `P_LocateFollowCam` `camparams.cz`
- [x] `P_NightmareRespawn`
- [x] `P_ParticleThinker`
- [x] `P_PlayerInSpecialSector`, `P_PlayerOnSpecialFlat`
- [x] `P_RespawnSpecials`
- [x] `P_SectorTouchesThingVertically`
- [x] `P_SetFollowCam`, `P_FollowCamTicker` `followcam.z`
- [x] `P_SpawnMobj`
- [x] `P_WalkTicker`, `P_ResetWalkcam` `walkcamera.z`
- [x] `P_XYMovement`
- [x] `P_ZMovement`
- [x] `PIT_AvoidDropoff`
- [x] `PIT_GetSectors`
- [x] `PushThinker::Think`
- [x] `PTR_AimTraverse`
- [x] `PTR_chaseTraverse`
- [x] `PTR_ShootTraverseVanilla`, `P_Shoot2SLine`, `PTR_ShootTraverse`
- [x] `R_1SidedLine` 1-sided linedef portal situation
- [x] `R_FakeFlat`, `R_SectorColormap`, `R_ProjectSprite`: sloped transfer_heights
- [x] `R_ProjectParticle`
- [x] `RIT_checkMobjProjection`
- [x] `ScrollThinker::Think`
- [ ] sloped anchor portals (see `R_DefinePortal` too)
- [ ] sloped horizon portal rendering
- [ ] sloped linked portals
- [ ] sloped portal overlays
- [x] `VerticalDoorThinker::Think` floor height

NEED TO CHECK (uncertain):
- [ ] `Add_Scroller`
- [ ] `CeilingWaggleThinker::Think`, `EV_StartCeilingWaggle`
- [ ] `EV_BuildStairs` step height setup
- [ ] `EV_DoFloor` absolute floor movement
- [ ] `EV_DoParamDonut` floor height lookup
- [ ] `FloorMoveThinker::Think` delayed stairbuilding
- [ ] `FloorWaggleThinker::Think`, `EV_StartFloorWaggle`
- [ ] `P_CreateSectorInterps`
- [ ] `P_MoveAttached`
- [ ] `P_SaveSectorPosition(s)`
- [ ] `R_AddLine`, `R_Subsector` surface height checks
- [ ] `R_DrawSpriteInDSRange`
- [ ] `R_RenderMaskedSegRange`
- [ ] `R_setSectorInterpolationState`
- [ ] sloped plane portal rendering?
- [ ] `T_MoveFloorDown`, `T_MoveFloorUp`, `T_MoveCeilingDown`, `T_MoveCeilingUp`

NOTES:
* 3dMidTex y offset and clipping heights can't use the slopes, it will just be relative to the editor sector heights.

PROPOSITIONS
* Collision model: decide how slopes should block actors. There are three ways:
1. Block completely: the thing's bounding box rests completely above slope. This is consistent with behaviour against walls and sectors and results in smooth movement when clipping against linedefs.
2. Block only the Z axis. A thing base's centre will always be at floor level. This is closer to a legged actor's model where some legs are bent higher than others to stand on a slope. But it will look funny with wide monsters and steep slopes, and it will bump against any step linedefs.
3. A compromise between 1 and 2, where only about 50% of width is clipped by slopes
* Friction model: decide when should slopes become slippery (make things fall off them), unclimbable. Should moving against a slope also be tougher than moving on horizontal terrain? Keep in mind that classic steps produce no such hindrances!

It makes sense that monsters should check their "monkeys" compatibility setting to determine if they can walk on slopes or not. Dropoff calculation should be like usual, and it will be _highly_ dependent on the chosen collision model.

**Comment by ioan-chera** [comment]
Something to keep in mind: slopes need to be updated, at least, to move vertically together with the sector.

**Comment by ioan-chera** [comment]
Another thing to keep in mind: sloped transfer_heights sector surfaces.

**Comment by Altazimuth** [comment]
How does such a behaviour work in zdoom? We want to try make the transition between the two smooth, and there's no gotchas.
________________________________

**Comment by ioan-chera** [comment]
If GZDoom uses slopes for transfer heights, it's probably something similar to 3D floors (which use slopes), i.e. the same plane is copied into the target area (this is the easiest way to think about).

If it does not use them, it means it's just a missing feature. Any use of slopes in transfer_heights control sectors in GZDoom maps would be completely accidental and useless.

I may check if GZDoom uses slopes for transfer_heights, but if it doesn't, then I see no problem adding this extra functionality to EE (if it's not added already, I should check).

**Comment by ioan-chera** [comment]
Another thing to keep in mind: sloped portal overlays. Currently not even semitransparent ones are supported.

**Comment by ioan-chera** [comment]
Largely done. We'll open other issues for other problems.
