### ISSUE TITLE
Wiki still lists hud_messagealignment

### ISSUE THREAD

**Issue by hfc2x** [team-eternity/eternity#451]
Hey there.

I don't know if this qualifies as an issue, or if it was an accident (since I haven't been able to find the commit where it was removed), but the console command hud_messagealignment doesn't work and isn't present anymore in Eternity. I tested both the latest official build and the latest development build, and I couldn't find a way to change the alignment of the centered HUD messages. I looked it up and the wiki mentions that the console command hud_messagealignment serves this purpose, and accepts integer values 0 to 2. However, the wiki is incorrect, since this command doesn't seem to exist in Eternity anymore.

Either the command may need to be restored, or the wiki edited to reflect the changes.

**Comment by Altazimuth** [comment]
I don't see mention of hud_messagealignment on the wiki, where is it? It's supposed to be hu_messagealignment, without the d.

**Comment by hfc2x** [comment]
My bad, it's indeed hu_messagealignment, and it's listed [here](https://eternity.youfailit.net/wiki/List_of_console_commands).

**Comment by Altazimuth** [comment]
Ah fair. No worries.
