### ISSUE TITLE
midiproc is not included in the CMake build process

### ISSUE THREAD

**Issue by hfc2x** [team-eternity/eternity#452]
May not be an actual issue, and simply something I'm doing wrong on my end. I downloaded the latest development build, but no Midiproc is included with it (and neither with the other packages listed at the DRD Team website). Therefore, music is completely impossible to balance in that version, mostly because it's incompatible with the Midiproc included with the latest official build.

Tried compiling the source myself, but I couldn't find any way of building midiproc.exe on its own, only Eternity.exe. Is there a way I can build a compatible midiproc.exe with the provided build scripts?

**Comment by Altazimuth** [comment]
The devbuilds never included midiproc, as it was never in the CMake build process.

**Comment by hfc2x** [comment]
Can it be included there, or is it out of the scope for said builds?

**Comment by Altazimuth** [comment]
It's probably possible though requires messing w/ the CMake. I keep meaning to do it but also keep forgetting, or I find something else to do.

**Comment by Altazimuth** [comment]
I'm going to take the liberty of changing the title.

**Comment by Altazimuth** [comment]
🦀midiproc is dead🦀
