### ISSUE TITLE
Scrolling linetypes 223/224, arg2 go wrong

### ISSUE THREAD

**Issue by simc2** [team-eternity/eternity#470]
The arg2 values for the linetypes 223 scroll floor and 224 scroll ceiling seem to be flipped.

- - - - - - - -
The [wiki](https://zdoom.org/wiki/Scroll_Floor) has:

line version:
223:Scroll_Floor (tag, scrollbits, type, x-move, y-move)

scrollbits: Selects the type of scroller and how the speed and angle is determined. (Only when placed on a line)
bit 0(1): Displacement scroller
bit 1(2): Accelerative scroller
bit 2(4): Use this linedef to get dx and dy
- - - - - - - -

In Eternity if the scrollbits has the value 1 or 5 the result is the accelerative. For values 2 or 6 it's the displacement scrolling. 

A test wad for Doom2 map01. 
[223+224.zip](https://github.com/team-eternity/eternity/files/5580328/223%2B224.zip)

From left to right:

The 1st switch, 223 scroll floor:
The medikit close by the player is on a floor controlled by a scroller with arg2: 1 (= displacement).
The medikit farther away has floor with arg2: 5 (= displacement).

The 2nd switch, 223 scroll floor:
The medikit close by, arg2: 2 (=acceleration).
The medikit farther away, arg2: 6 (=acceleration).

3rd and 4th swicthes, 224 scroll ceiling, arg2s in the same order: 1 and 5, 2 and 6.

Compared with Eternity 4.01.00, GZDoom 4.5.0 and ZDoom 2.8.1.

**Comment by Altazimuth** [comment]
I'd suggest comparing with PRB+, though this probably is an actual EE issue. EE's scrollers are Boom scrollers, which are very much not the same as ZDoom's.

**Comment by simc2** [comment]
In a Boom format map both linetypes 248 scroll floor/sector height change and 217 accelerate floo/sector height change 
work right in PrBooms and Eternity. Here's a test wad for that too:
[217+248.zip](https://github.com/team-eternity/eternity/files/5580390/217%2B248.zip)

That zip has two wads. boom_217+248.wad is a Doom/Boom format map. 217+248Z.WAD is the same wad opened in ZETH/Dosbox and saved in there as Doom/Hexen format. In Eternity it behaves exactly the opposite than the Boom format map. In ZDoom they both work the same.

**Comment by simc2** [comment]
ZETH is old, but it converts Boom types 248 and 247 (scroll/accel both floor and things on sector height change) to 223 scroll floor with arg2: 5 and 6 and arg3 to scroll both floor and things.

**Comment by Altazimuth** [comment]
OK. Should be an easy fix ideally. Will be looked into. Thanks for the report.

**Comment by simc2** [comment]
Oh, of course it is **arg1**, not arg2. Sorry.

223:Scroll_Floor (tag, scrollbits, type, x-move, y-move)
224:Scroll_Ceiling (tag, scrollbits, unused, x-move, y-move)

**Comment by Altazimuth** [comment]
So the wrong sector(s) is/are scrolled? Is that the entirety of the issue?

**Comment by simc2** [comment]
No, just the numbering of the args is started from arg0. The udmf format has:

linedef // 308
{
v1 = 305;
v2 = 310;
sidefront = 365;
special = 223;
arg0 = 186;
arg1 = 5; <-------------- This gets swapped to 6 in EE
arg2 = 1;
playercross = true;
blocking = true;
}

Tag is arg0, scrollbits arg1, if that has any meaning. I should have been more precisely with this the first place.

**Comment by Altazimuth** [comment]
Ah right null indexing right right.

**Comment by ioan-chera** [comment]
Fixed this now. BIG PROBLEM HOPEFULLY NOT
