### ISSUE TITLE
Automap crosshair is off center

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#473]
See `AM_drawCrosshair`. It fails to draw the dot at the center of the display. This was seen under geomstring `800x600w`, not limited to this though.

**Comment by GastonLahaut** [comment]
As reported before: the actual weapon hud crosshair is also off center. Easily seen with perfect aim hitscans: puff appears in the lower right quadrant of a crosshair instead of center.

**Comment by Altazimuth** [comment]
> 
> 
> As reported before: the actual weapon hud crosshair is also off center. Easily seen with perfect aim hitscans: puff appears in the lower right quadrant of a crosshair instead of center.

Unrelated.
