### ISSUE TITLE
Preamp gain somehow set to 0.00 by itself

### ISSUE THREAD

**Issue by tomash** [team-eternity/eternity#495]
Hello. Great project, I stumbled upon it thanks to MtPain27 and his recent video about Heartland.

There is a weird issue that I stumbled upon on Ubuntu (20.04), happening both with 4.02.00 and current master (e677e67878d4ce2b761f79867da665a1a0462d3c): Eternity launched fine, everything works, I go to the options to configure resolution, mouse sensitivity and start playing. I also turn down the music volume a bit. Playthrough goes fine. But when I start eternity again, I get no sound (no effects, no music, complete silence). There are no error messages in bash console, everything seems fine, I confirmed sound works in system, browsers and in prboom-plus.

After walking through sound options I noticed my Preamp Gain was set to 0.00, moving it to 0.10 and more brought back all the sound. I did not touch this option, hence filing this issue.

I'll re-test if this happens on Windows as well, as soon as I get to my Windows machine later today.

**Comment by tomash** [comment]
Funny: it seems to happen (set Preamp Gain to 0.00) every time I run eternity. Setting it in the menu does not persist.

My system.cfg has this:
```
[0-1(0,93896)] Preamplification factor
s_eqpreamp                0,00000
```

And now the fun part:

* if I set it to 0,10000 or 0,20000 in this file, it gets ignored and the game launched with 0,00 preamp gain
* if I set it to 1,00000, the setting is applied and the game launches with 1,00 preamp gain
* ...if I then turn it down to 0,20 in the game options and exit, the file contains the new value 0,20000, but subsequent launch of the game is silent again, see the first bullet point

Also, I have no idea why comma instead of dot is used as decimal separator. It is consistent with polish locale, but it seems such decimal separator makes everything past the separator ignored by the game.

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_MEASUREMENT=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LC_ALL=
```

**Comment by tomash** [comment]
Yep, I had a good hunch, it's the locale. Launching the game with
`$ LC_ALL="en_US.UTF-8" eternity`
makes the values display in-game with dot as decimal separator, after quitting the numbers in config file have dot as decimal separator, and every subsequent launch of eternity (with this locale env) uses proper Preamp Gain, as saved in the file -- here `0.20000`.

It seems the way to fix it is to either not use the locale when saving values in config file, or use it also when reading them from the config file.
I'd submit a pull request but my C++ is very rusty, and it's not even a rustlang pun, I'm a web developer who's been working with dynamic languages for the last decade.

**Comment by Altazimuth** [comment]
Wow, nice sleuthing. Thanks a lot for the report and for figuring out the cause.
By pure coincidence I set up a Linux Mint VM the other day. I'll try look into this.

**Comment by Altazimuth** [comment]
I believe I've fixed it, or at the very least can't reproduce on my VM with the latest commit (there's no audio but that's a VM thing, the settings are all correct).
The issue appears to be that xlocale.h no longer exists, which I remedied by using locale.h instead if present and if not on Windows.

**Comment by tomash** [comment]
Confirming, built from latest master - 3e163cf58500a42bb350b3aa2dcac2f333b80ea2 - now stores, shows and reads locales with dot as decimal separator, regardless of LC_ env. Which makes Preamp Gain persisting and no longer being reset to zero.
Thanks!

**Comment by Altazimuth** [comment]
Glad to help. Thanks again to you, as well.
