### ISSUE TITLE
Widescreen Asset Support?

### ISSUE THREAD

**Issue by OpenRift412** [team-eternity/eternity#500]
I think it's kind of a shame that the Eternity Engine doesn't have support for widescreen assets. I think it could really be the cherry on top for completing the clean, modern Doom experience. Not to mention the HUD shortcomings you can have with running Heretic in widescreen. Would this be doable?

**Comment by Meerschweinmann** [comment]
The widescreen support for DOOM, DOOM2, TNT and Plutonia works flawless now. 
Had testet the named games with my 32:9 super-ultrawide assets.
Even the bunny-screen from DOOM works perfect with the official Unity and Kex WAD "bunny-screen PFUB1/PFUB2 arrangement" since today.
