### ISSUE TITLE
DRDTeam DevBuilds not working

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#501]
Between commits 9ac0c3f6 and 3370f229 something happened that prevents https://devbuilds.drdteam.org/eternity/ builds from working. Here's the diff between them:

[devbuild-breaking-change.diff.txt](https://github.com/team-eternity/eternity/files/6369456/devbuild-breaking-change.diff.txt)

Here's the log of 3370f229: 
[eternity-4.03.00-pre-163-g3370f229.log](https://github.com/team-eternity/eternity/files/6369464/eternity-4.03.00-pre-163-g3370f229.log)

And the log of its next commit, 1972609e: 
[eternity-4.03.00-pre-192-g1972609e.log](https://github.com/team-eternity/eternity/files/6369463/eternity-4.03.00-pre-192-g1972609e.log)

**Comment by Altazimuth** [comment]
It's a CMake issue, seemingly due to outdated CMake on his machine. Closing because it's not on us. I've contacted Blzut3 about this. Please in future like, give me at least a day to try look into something before filing a bug, as it just clutters things up.
