### ISSUE TITLE
Short sky needs to be adjusted to look correctly with the increased pitch range

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#505]
UPDATE: there are several problems we're facing, so here's a list of things to do:

- [x] Fix rendering of PrBoom-targeted tall skies to look like in Doom, potentially filling the whole screen when looking ahead, instead of shifted up like in Heretic/Hexen (and GZDoom too). Do this by **detecting if the tall sky is set by EMAPINFO**, in which case use the Heretic rule (rendered from the 32-degree look area). If the sky is merely a SKY1-SKY4 replacement via patches or TEXTUREx, then apply the Boom rule. Only do this in the DOOM game mode (possibly via a game info flag).
- [x] Add an EMAPINFO option to control the vertical offset of the skies.
- [x] Implement sky fading to a single color when looking _up_ (but not down) instead of tiling or stretching. May probably be done by avoiding drawing above a column's texmid point (100 = top of the screen; 200 = top of the Heretic field of view) (NOTE: my branch mentioned here isn't optimal, since it just bakes new textures internally — I'd prefer something that draws directly, though some fading would be good)
- [x] check that MBF sky transfers with downwards offsets still look as intended when looking ahead
- [x] check that MBF vertically scrolling skies still work as intended 
- [x] fix a crash happening with lava flats as skies
- [x] Raise the view pitch back to 45 degrees down and up. Set up game mode info OR player class EDF info to have different view pitches. For Heretic it would be best to preserve the 32-degrees pitch, because both its gameplay and rendering were made for this range. We should be able to extend it to 45 in mods. **UPDATE**: settled to only add EDF gameproperties for this.
- [x] Decide what to do about the obsolete `r_stretchsky` CVAR. [**Decided to stub them out, they still exist, but are documented as deprecated and do nothing**]
- [x] Prepare the wiki documentation

OLD TEXT HERE:

With the increased pitch range, unfortunately the skies also need to stretch even more (and 200 px may no longer be sufficient). See here:
![etrn78](https://user-images.githubusercontent.com/3496907/116699091-da40c600-a9cd-11eb-83ac-31d6f0527c50.png)

However, by stretching, they would look like this now:
![etrn59](https://user-images.githubusercontent.com/3496907/116699139-e7f64b80-a9cd-11eb-8390-e4b493544bdd.png)
(this is an experimental screenshot, not part of any commit. I tested by changing in `r_plane.cpp` the following value to use:
```
      return M_FloatToFixed(view.pspriteystep * 0.38f);
```
0.38 instead of 0.5 (caution: there are three places).

**Comment by Altazimuth** [comment]
Is it possible to do dynamic sky stretching based on current pitch?

**Comment by ioan-chera** [comment]
I imagine it would look optically weird. Another suggestion on the chat was to try and do like GZDoom's (is it also on software? I don't know) new way of extending the top part of the image to fill the upper rows.

**Comment by ioan-chera** [comment]
Branch name: **sky-padding-implementation**
