### ISSUE TITLE
Add compressed ZDBSP support

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#520]
There are wads which claim to work on common feature ports like PrBoom+, but use compressed ZDBSP nodes, which currently aren't supported by Eternity (it only supports uncompressed). For example, there's [Thatcher](https://thatchers-techbase.github.io/get.html) MAP02.

**Comment by Altazimuth** [comment]
Note: Only Thatcher's Techbase 1.0 has this issue. 1.1 resolves it. Attached is 1.0.
[THATCHER.zip](https://github.com/team-eternity/eternity/files/7229985/THATCHER.zip)

**Comment by Altazimuth** [comment]
We got a new one https://www.doomworld.com/forum/topic/133295-boom-the-diseases-and-casualties-this-year-being-1632-11-maps-v11/
