### ISSUE TITLE
Pitch black rooms aren't pitch black

### ISSUE THREAD

**Issue by muizzsiddique** [team-eternity/eternity#522]
This is a gamma corrected screenshot (it's more obvious than this), but when playing the game (just like PrBoom+) pitch black rooms are effectively visible. This isn't the case with Chocolate or Crispy Doom.

You can see the shape of the room including some detail in the texture. This makes it very easy to navigate pitch black rooms.

![Screenshot 2021-10-02 203834](https://user-images.githubusercontent.com/23620568/135729890-83b77efc-4ae2-4b0d-aa31-3de1990ea4d6.png)

**Comment by neonvortex** [comment]
I tested with Chocolate Doom and Eternity and got identical results. I'm fairly sure this is the intended appearance.

![image](https://user-images.githubusercontent.com/75443150/135864006-da10a510-6eed-45a0-8fc1-5089923c4a7b.png)

**Comment by muizzsiddique** [comment]
I just tried it on Chocolate and Crispy Doom and it's as you say... I don't remember it being like this though.
