### ISSUE TITLE
Lost souls spawning inside the player with 3D clipping on raises the player

### ISSUE THREAD

**Issue by simc2** [team-eternity/eternity#530]
The player gets lifted upwards when a close by pain elemental tries to spawn a lost soul. Happens repeatably in 4.0.2 and atlatest recent 4.03.00-pre-413-gf897efea without configs. Setting things infinitely high will prevent this happening..

Here's a test wad with a demo. In it the pe helps the player to raise on a 42 mu high floor
[pe-lift.zip](https://github.com/team-eternity/eternity/files/7437279/pe-lift.zip)
.

**Comment by Altazimuth** [comment]
Fixed by 5fb1977ca5f9a0e6ba3148d87bc5d624aa242146
