### ISSUE TITLE
[Saving] Implement a level integrity check

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#538]
Make it so saves store enough information so that loading the game only works if the required wads are present. Doing this would greatly help with making multiple save games from multiple mods, without the risk of crashing Eternity if loading the wrong game.

How it can be done? Do not store the file name (_except for error reporting_), and do not store a hash. This would cause the integrity check to be too strict or maybe even inaccurate in some cases. Instead, check before loading the level (the "world") that the number of items matches the ones from the map. Check that everything that's getting loaded is going to fit the current level. If it doesn't, we can either choose to stop loading data (most likely keeping the player at the given level in a cold-start state), or error out. The error or warning message may contain hints such as the command-line which was used for the wad.

**Comment by Altazimuth** [comment]
Fixed by 931b778ccfb0d26fc54fc47cd0bcc99cb6e780fb
