### ISSUE TITLE
Weird scrolling floor direction drift

### ISSUE THREAD

**Issue by andrikpowell** [team-eternity/eternity#544]
I have a map that I'm working on that utilises a constantly conveyor for a spinning tower, and in PrBoom Plus and GZDoom (yeah I know), the conveyor works fine...

But for some reason in Eternity (tested both 4.02 and 4.03), the voodoo doll in the conveyor has a weird drift to the east side of the map, even though the scrolling floor is directly heading south.

Here is a short video showing the object slightly drifting to the east:
https://www.youtube.com/watch?v=GQE8gwBzXyU

Although in this video, it didn't really cause issues with the conveyor, I have had the voodoo doll get stuck on the wall and stop the constant conveyor. The conveyor uses "244 WR Teleport to line with same tag (silent, same angle)".

I mention this because I'm pretty sure many boom pwads use this kind of conveyor system for automated lights or moving platforms (Sunlust map29), and this slight drift could break that functionality in those wads.

**Comment by Altazimuth** [comment]
Could you please give the parameters of the line that sets this up? The x and y distance from the first to second vertex, and which way the line is flipped.

**Comment by andrikpowell** [comment]
I assume you asking about the scrolling line.

Top vertex:
X 7656
Y 1376

Bottom vertex:
X 7656
Y 944

The linedef is 432 units in length and is pointed west.

Here's an image:
![Screenshot (341)](https://user-images.githubusercontent.com/61759217/142747963-057b2c80-5087-4b74-82c1-9a807d5ea95a.png)

If you'd like I can send the wad over.

**Comment by Altazimuth** [comment]
The WAD shouldn't be necessary for now. I'll see if I can try repro it at some stage.

**Comment by simc2** [comment]
It likely happens because the teleported item's momentum after teleporting is calculated with the imprecise finesine/cosine table.

When scrolling to directions 0, 90, 180 or 270 the drift effect can be cancelled by setting the first value (25) and the 8192nd value (-25) to zero in the finesine table in tables.c(pp). But that can't be an acceptable answer and the drift still happens when scrolling to other directions.

This happens in most Boom ports: https://github.com/coelckers/prboom-plus/issues/417

**Comment by andrikpowell** [comment]
simc2 is correct.

I just tested the map in PrBoom and the drift exists there as well...
I guess I never noticed it, cuz in PrBoom when the voodoo doll was drifting to the east, it never got stuck...

The only reason I noticed the drift in Eternity, was because the voodoo doll actually got stuck on the east wall of the conveyor room during one of my map tests, stopping the conveyor altogether. (Though I'm having some trouble trying to recreate the stuck voodoo doll).

**Comment by Altazimuth** [comment]
This means that things'll stand where they are. I'm going to take the initiative and close this, as it's a pretty fundamental behaviour. Sometimes I wonder how using a more accurate set of trig tables would play out in modern demos, but for the moment things will stay as they are.
