### ISSUE TITLE
DOOM Barrels' corrected height breaks compatibility with maps expecting 42

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#568]
Due to barrels having `correct_height` of 34 instead of their original `height` of 42, some maps may break due to failing to make chain reactions. We need to somehow fix this.

**Comment by sink666** [comment]
which maps in particular? a list of test cases would be helpful, i think this could be solved

**Comment by ioan-chera** [comment]
Fixed for great justice. Barrels are now properly 42 units tall, without any supposed corrections made for aesthetic reasons that break gameplay.
