### ISSUE TITLE
Restore pre-SMMU colourmapped deep water or high sky sectors

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#57]
SMMU changed it to ZDoom-like coloured sector effects, and I suspect it was wrong to do so, so I'll try restoring the old behaviour

**Comment by Gaerzi** [comment]
ZDoom keeps the Boom behavior intact, and has a different way to setup colored sectors.

**Comment by ioan-chera** [comment]
I simply mean that SMMU makes the sectors have coloured lights similar to how such lights look like in ZDoom (wasn't ZDoom popular back then for its coloured sectors?). No blame intended on ZDoom.

**Comment by haleyjd** [comment]
The "old" behavior is already in the engine and is currently a cvar. I suggested changing this into an EMAPINFO setting a while back.

**Comment by ioan-chera** [comment]
Solved: https://www.doomworld.com/forum/topic/93581-possible-modifications-to-the-boom-transfer-colormap-behaviour/?do=findComment&comment=1733696
