### ISSUE TITLE
Loading some saves causes sprites to glitch out. Seems to be WAD+DEH saves.

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#570]
It seems to happen with WAD + DEH saves.

![image](https://user-images.githubusercontent.com/3496907/187266290-a01abe0a-b5e5-4391-b401-c9c2b6d71c99.png)

Also ammo from the map seems to be lost after loading.

Apparently it happens with Ray Mohawk 2: https://www.doomworld.com/idgames/levels/doom2/megawads/mohawks2

No problem with other ports (e.g. DSDA-DOOM), so this is clearly an Eternity bug.

It also happens with this WAD: https://www.doomworld.com/forum/topic/131061-malevolence-episode-1-9-maps-boom-compatible/

It does not seem to happen with Mayhem18P.wad: https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/mayhem18p

**Comment by devinacker** [comment]
Seems to have been fixed by 0bd4853cc3c8e1d1990ee276159039c16f084754 (at least for KDiKDiZD, which had the same issue)

**Comment by Altazimuth** [comment]
Oh good call, yeah this was fixed, thanks!
