### ISSUE TITLE
Demo desync on crazyMaze.wad

### ISSUE THREAD

**Issue by jackrjli** [team-eternity/eternity#577]
I was trying out the large maze map posted in [this thread](https://www.doomworld.com/forum/topic/132602-i-believe-i-have-created-the-largest-and-densest-maze-possible-in-doom/) on Doomworld (specifically the edited version by Benjogami), and found that in other demo-compatible source ports (dsda-doom, Crispy Doom, Woof) the enemies could not see the player except when the player's standing in the small square at the start, but in Eternity they can see the player. This results in demos recorded in one desyncing in the other. For example, [this demo](https://github.com/team-eternity/eternity/files/10077720/crazymaze.lmp.zip) I recorded survives until the end of the demo (a bit over a minute) in the aforementioned other ports but dies in about 24 seconds in Eternity.

**Comment by ioan-chera** [comment]
The map has a zero sized `REJECT` lump! This would result in undefined (arbitrary) behavior in vanilla, with monsters reacting in unpredictable ways depending on whatever happens to be in memory. Maybe it's worth checking what DSDA-DOOM is doing to best emulate this undefined behaviour.

**Comment by ioan-chera** [comment]
`-reject_pad_with_ff` (https://eternity.youfailit.net/wiki/List_of_command_line_parameters#Demos) does *not* solve this.
