### ISSUE TITLE
Restore pre-MBF point pushers and pullers

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#58]
I suspect Lee changed them for the worse for no good reason.

**Comment by Gaerzi** [comment]
Don't forget about friction! In Boom, monster movement is unaffected by low/high friction; in MBF they are. In ZDoom, [the same compatibility option](http://zdoom.org/wiki/Compatibility_options#compat_mbfmonstermove) handles both monster friction and monster pushers/pullers. You might want to separate them by I don't see a point in that; monsters are either affected like in MBF or not affected like in Boom.

**Comment by ioan-chera** [comment]
Some of the Boom weather effects are settable in MBF through compatibility and monsters settings. I think it's the "Monsters are affected by friction" monster setting in MBF.

**Comment by ioan-chera** [comment]
Closed: it's an old issue which may not be important right now. Counts more as a feature request really.
