### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Python-Sargent** [team-eternity/eternity#592]
is this an error on my side, not having a dependancy?

`

> [ 76%] Building CXX object source/CMakeFiles/eternity.dir/s_sndseq.cpp.o
> [ 77%] Building CXX object source/CMakeFiles/eternity.dir/s_sound.cpp.o
> [ 77%] Building CXX object source/CMakeFiles/eternity.dir/sounds.cpp.o
> [ 77%] Building CXX object source/CMakeFiles/eternity.dir/sdl/i_input.cpp.o
> [ 77%] Building CXX object source/CMakeFiles/eternity.dir/sdl/i_main.cpp.o
> /home/user/eternity/source/sdl/i_main.cpp:23:10: fatal error: SDL_net.h: No such file or directory
>    23 | #include "SDL_net.h"
>       |          ^~~~~~~~~~~
> compilation terminated.
> make[2]: *** [source/CMakeFiles/eternity.dir/build.make:3691: source/CMakeFiles/eternity.dir/sdl/i_main.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:369: source/CMakeFiles/eternity.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2
> [user@computer build]$ 

purposely removed my info
`

**Comment by Altazimuth** [comment]
Looks to be it. What distro you on?

**Comment by Python-Sargent** [comment]
sorry for the late answer, I'm on Manjaro, ARCH-Linux, running on a M2A-vm
HDMI

**Comment by Altazimuth** [comment]
In that case just doing `sudo pacman -S sdl2_net` should do it? Ideally it'd yell at you if you lack the libs when generating CMake. I may need to look into that later.

**Comment by Python-Sargent** [comment]
OK, thanks, sorry for the late reply, I'll try this soon.
