### ISSUE TITLE
How do I disable walking on the mouse? And also a suggestion to add always run, or is this feature in the port?

### ISSUE THREAD

**Issue by DENCHIKTEAM** [team-eternity/eternity#599]
Hi, this port is good. But what always annoyed me in the original and in some ports, is the non-disable mouse walking. I would also like to see an option that allows you to always run instead of holding shift.

**Comment by ioan-chera** [comment]
You can disable mouse moving in the mouse menu under the options menu. It is disabled by default when downloading Eternity, but it's possible your settings were already to enabled.

You can enable always running with the `autorun 1` console command. You can also make then "run" command make you actually walk by using the `runiswalk 1` console command.

**Comment by DENCHIKTEAM** [comment]
Thanks for your help! Good luck with further development

**Comment by DENCHIKTEAM** [comment]
Does eternity not support widescreen assets? Because when I try to run Doom 2 with them I get this image cropped, even though it should be full screen in 16:9 format.
![Screenshot_32](https://github.com/team-eternity/eternity/assets/51756144/e409549f-a3cf-4896-9687-72a9817e179d)
