### ISSUE TITLE
Linedef with two sides and missing Double-Sided flag does not block LOS checks

### ISSUE THREAD

**Issue by akorov** [team-eternity/eternity#601]
Sample wad: [oneside.zip](https://github.com/team-eternity/eternity/files/12528396/oneside.zip)

In DOOM2.exe and a wide variety of ports - chocolate, crispy, prboom-plus, dsda-doom, woof, gzdoom, doom retro - a linedef with two sides and missing Double-Sided flag will block LOS checks.

![image](https://github.com/team-eternity/eternity/assets/11968110/0f79b9e5-8bd4-4fa4-a7f8-bde2cf266145)

In sample wad on executables mentioned above arch-vile will stay dormant, if woken up will only target player on the same side of the wall and vile's attack will not complete if the wall is crossed over to the other side. On Eternity Engine (tested on x64-4.03.00-pre-1227-gd699a7d92) vile will immediately become active and the wall will not block sight or attacks in any way.

**Comment by ioan-chera** [comment]
Fixed, keeping in mind Heretic support.
