### ISSUE TITLE
DOOM wide bunnyscreen works only in one of two arrangements

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#620]
Hello again :)

While making some widescrren assets for up to 32:9 i have noticed, that in the wild there are two possible arrangements of the bunnyscreen-ending.

The Unity DOOM.WAD and Nash Muhandes Widepix offer a 320 pixel wide PFUB1 and then a wider PFUB2 (426 Unity, 560 Widepix).
That arrangement does not work with Eternity Engine.

Then there are the downloadable Bethesda widescreen assets that offer equal sized PFUB1 and PFUB2. Both 560 pixels and they overlap in the middle.
I am working on some so called Ultra-Widerpix854 assets for aspect ratios up to 32:9 with PFUB1 and PFUB2 in both 854 pixels width. 
These arrangements works with Eternity Engine.

But even my assets work, would it be not better that those other assets work too?
Even the Unity DOOM.WAD contains unequal picture sizes as official release.

Here i have made a zip file with both possible ways.

One WAD has equal sized PFUB1 and 2, the other has different sized PFUB1 and 2.

[Bunnyscreen_Arrangements.zip](https://github.com/user-attachments/files/16216296/Bunnyscreen_Arrangements.zip)

**Comment by Meerschweinmann** [comment]
Update: The new official DOOM + DOOM2 release has the same arrangement of the bunny-screen as Unity had. 
So unfortunately EE can not handle this bunny-screen.

**Comment by ioan-chera** [comment]
I modified the code to be smarter and tested it with the official new DOOM WAD with its widescreen assets, and now it looks good, at any resolution. I didn't test other wads. Does it work for you?

**Comment by Meerschweinmann** [comment]
Hooray :)

I can confirm that my 32:9 assets work fine with the PFUB1 320pixels and PFUB2 854pixels width arrangement.
I had tested with these assets in different aspect ratios (5120x1440, 3440x1440 and 2560x1440).
EE had successfully arranged these super-ultrawide assets in every aspect ratio and cut the correct pixels left and right not needed.

The overlapping arrangement does not work anymore, but when i had to choose between those two possible arrangements i would choose arrangement that came with the official Unity and Kex release.
So when someone is using these official WADs, the Bunny screen works.

**Comment by Meerschweinmann** [comment]
One thing that comes a bit up with 21:9 and even more 32:9 is that Daisy's spiked head comes to early on screen (21:9) or is shown before scrolling begins.
That is not an EE specific problem. That is caused because of the fact that the scroll area is only 320 pixels wide.

I had drawn a PFUB219 (72pixels wider) and PFUB329 (216pixels wider). So spiked Daisy is the same amount of pixels out of screen as she is  in 16:9 ratio.

Only thing that misses is a sourceport that is able to scroll longer ;)
The time before the "THE END" patch is shown could be enough to scroll longer.

![PFUB952_72added](https://github.com/user-attachments/assets/01b0c710-cf34-414d-9015-7692c3ec278e)
![PFUB329_216added](https://github.com/user-attachments/assets/aa7642bd-3890-4303-bba8-1eb20fe719fd)

**Comment by ioan-chera** [comment]
Problem is that there isn't enough information to know when to scroll longer. This would have to get scripted someday, because there's also the Heretic ending arrangement to support. Right now I have to prioritize DOOM + DOOM II style, where it moves 32 units in the center, with accepted cropped margins. What you suggest would work if the start and end positions are at the extremities, with increased scrolling speed so it takes the same time to get there. Keep in mind it needs to stay in sync with the music. It might look funny if it moves very fast though.

**Comment by Meerschweinmann** [comment]
Good morning 😃

I had thought about scrolling faster depending on the width extension too, to get sync with the music. But looking at the bunny scroll again and again, i noticed that when scrolling much faster, the point when Daisy gets on screen will be destroyed. Even the bunny screen was designed for 4:3 aspect ratio it works really fine with 16:9. So i made those two Pictures with Daisy the similar amount of pixels out of screen like she is in 16:9 to not extend the middle part even more when choosing 4:3 as base.

In my opinion there are two points in the bunny screens music that are important and should not be changed. When comes spiked Daisy in the Screen area and when comes the "THE END" patch.

Normally the "THE END" patch shows up some time after the scrolling ends. This time could be used to scroll longer. Hopefully it is long enough to scroll for the PFUB329. PFUB219 should be No Problem.

My idea is that when PFUB219 and PFUB329 are not present everything behaves like it is now.

When a PFUB329 in an PWAD is present and a width to height ratio bigger 3.5 is present this PFUB329 is used and scrolled from right to left.
Same for PFUB219 and width to height ratio range of 2.3 to 2.4 to Cover all so named 21:9 ratios up to 24:10.

When PFUB329 and PFUB219 are not present and any above named width to height ratio is present PFUB1 and PFUB2 are used as usual.

**Comment by ioan-chera** [comment]
Closing this until we get new problems.
