### ISSUE TITLE
Eternity Engine wrong FOV with 32:9 monitor.

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#621]
Hello.

When using Eternity Engine with 32:9 monitor the FOV default is wrong.

It has to be set in console with R_FOV 139 to look like it does in International DOOM, Woof, Odamex and GZDoom.

This happens every startup.

Here are two pictures. One shows the FOV set at 139, the other FOV at default.

![FOV139](https://github.com/user-attachments/assets/cb152837-aeaa-4f3a-99bc-3fa6ed28139e)
![FOVdefault](https://github.com/user-attachments/assets/c58e87a8-10fd-4553-a18a-154b16e886f4)

**Comment by ioan-chera** [comment]
Unfortunately the equation to get `fov` seems to be the following:

```
   // The general equation is as follows:
   // y = mx + b -> fov = (75/2) * ratio + 40
   // This gives 90 for 4:3, 100 for 16:10, and 106 for 16:9.
   fov = static_cast<int>((75.0/2.0) * ratio + 40.0);
```
It has a very special case for 320x200 and 640x400 to keep it 90 degrees (as opposed to 100 as resulting from this formula).

Guess we need a better formula?

**Comment by Meerschweinmann** [comment]
One thing i had noticed meanwhile. When using 43:18 as aspect ratio (3440x1440). Everything seems fine with FOV. But going wider ist like there is something limiting the fov to rise higher. I had not compared the 43:18 ratio to other ports and count pixels in textures, If this is helpful. Same i had done with 32:9 to get the needed FOV of 139.

**Comment by ioan-chera** [comment]
Fixed. The formula was just a very raw polynomial approximation, which ran away when outside the range. Now it just uses the arctangent, as it should.

**Comment by Meerschweinmann** [comment]
Thank you :) Will test it tomorrow when the new version is downloadable at DRD devbuilds.
