### ISSUE TITLE
Status bar glitches with '-deathmatch' or '-solo-net'

### ISSUE THREAD

**Issue by inf78** [team-eternity/eternity#623]
Here is what I get when running Doom2 with Eternity and these CLI params: -solo-net -warp 01
![d2-solo](https://github.com/user-attachments/assets/dc57b667-869a-4882-ae98-10d70a57a88c)

And here with: -deathmatch -warp 01
![d2-dm](https://github.com/user-attachments/assets/76524868-1219-4f94-a0cf-1992125619b7)

If I just warp without any other arguments, no problem. And the problem is the same with Doom 1 (Ultimate), it's not only Doom2 related.
I run those with just the IWADs loaded and nothing else.
It seems the glitch is colored according to the selected player's color.

Linux, built from source downloaded 3 days ago.

**Comment by inf78** [comment]
I tried latest Win64 DRD build and the problem wasn't there initially, till I changed the resolution to a 16:9 one. And so I changed the resoltion to 4:3 1600x1200 on the Linux machine and yes, problem is not there.
So it seems to happen only with some non 4:3 ARs.

**Comment by ioan-chera** [comment]
Fixed, thanks.
