### ISSUE TITLE
Vaporware demo and Heartland = SIGSEGV

### ISSUE THREAD

**Issue by inf78** [team-eternity/eternity#624]
Both of these Eternity-specific wads will give me a SIGSEGV in Mageia 9 when loading the first map.
Vaprdemo will crash before the map loads, while Heartland will crash in less than a second after the 1st map is loaded.

I'm sure both were working just fine maybe a month ago or so, so it must be some recent change in Eternity that is causing this.

**Comment by ioan-chera** [comment]
I get the crash because I use `pSlopeHeights` array assuming the sector is part of the `sectors` array, when in fact it's the local `tempsec` structure, so it goes outside the buffer. I need to fix it maybe to compute slope heights just for tempsec, on the spot, if needed.

**Comment by ioan-chera** [comment]
Also got the same with Vaporware, but only without -warp or -nomusic (i.e. classic new game sequence instead). I fixed the problem, thanks for reporting it.
