### ISSUE TITLE
Visual portal glitches /w GetActorFloorZ / CheckActorFloorTexture

### ISSUE THREAD

**Issue by GastonLahaut** [team-eternity/eternity#625]
On latest builds only and displayed only on maps with overlayed portals ('underwater' sections). Build without issues: 1276 (july 24).  Using the ACS function GetActorFloorZ(0) or CheckActorFloorTexture(0,"blah") makes the portal boundary flats (linked, edge) either visually solid or flickering between solid and normal. Not just above overlayed portals, but everywhere especially when viewed from top. Game often crashes afterwards, or crashes during quitting.  Same map behaves normal with the above ACS functions not being called.

**Comment by GastonLahaut** [comment]
[CRASHLOG.TXT](https://github.com/user-attachments/files/16677518/CRASHLOG.TXT)

Crash during quitting by console command 'quit'.

**Comment by ioan-chera** [comment]
Closed as fixed
