### ISSUE TITLE
Resolution of 5120x1440 exceeds maximum renderer resolution limit?

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#626]
Hello again.

When choosing a video mode of 5120x1440 pixels and renderer resolution "native" EE crashes.

Choosing a video mode of 5120x1440 and a renderer resolution of 5048x1420 pixels EE works.

Going up to a renderer resolution of 5084x1430 works, but sometimes it crashes.

It seems that the resolutions or pixel count in this range are the limit for the renderer.

If it helps. The PC is a Ryzen 8700G with 32GB of RAM.

Btw: I was able to built the latest EE with the FOV fix from today. And hey, automatic FOV works great now. Thank you :)

**Comment by Meerschweinmann** [comment]
Btw. It would fine when the aspect ratio selection would contain 32:9. And some resolutions like 2560x720, 3200x900, 3840x1080 and 5120x1440. 
Me personally knows what my screens resolution is and what alternatives are there as 32:9 aspect ratio.

But it makes EE a bit more userfriendly for users that are not so aware about what they have.

**Comment by ioan-chera** [comment]
Apparently it was an overshooting error caused by coarse approximation. If resolution is 5090 or above, the scale value becomes too small before getting incremented by a flat value (1), so drawing the status bar (etc.) would hit `w` instead of `w - 1` as normal.

**Comment by Meerschweinmann** [comment]
Wow, that was fast. Thanks again!
