### ISSUE TITLE
Something got wrong with slope below sector-portal after last DRD-devbuild 1361.

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#627]
Hello again :)

Here is something not so fine i has noticed with the EE i had build this evening. With the last DRD-devbuild 1361 everything was fine, but something that happened after that build made problems with the slope below the sector portal, you can see in the screenshots.

![After_DRD1361](https://github.com/user-attachments/assets/13e47de4-38b5-4fad-ae37-307fa2ac2ff6)
![DRD1361](https://github.com/user-attachments/assets/0ffdf1d5-ad8f-4eb4-80c1-dcd7fdefac8c)
![UDB](https://github.com/user-attachments/assets/6fb2eece-258e-40f7-99ba-78faf506961d)

**Comment by Meerschweinmann** [comment]
Update:

looking at the slope directly, without looking through a portal, everything is fine with the newest selfmade build.

![etrn01](https://github.com/user-attachments/assets/0b727db2-6bbf-4bf8-a900-674703b6f6e6)

**Comment by Meerschweinmann** [comment]
Update 2:

Even the small slopes left and right on that black "roof" get errors when flying in the portal above their sectors and looking on them through a sector portal.

![etrn02](https://github.com/user-attachments/assets/b44ce020-7e07-4742-b74e-604f83564877)
![etrn03](https://github.com/user-attachments/assets/9948d7b8-95de-4fe3-ba46-cc64bd8edb2c)

**Comment by Meerschweinmann** [comment]
Here is a test-map i made some time ago. I added a little ramp with two slopes as start. When trying to look at that ramp from above the tower or using the fly mode, the latest EE crashes.

When using DRD-devbuild 1361 everything is fine.


[EE_portal_multifloor-lift.zip](https://github.com/user-attachments/files/16738062/EE_portal_multifloor-lift.zip)

**Comment by Altazimuth** [comment]
Note: 1361 is b340ea2d6. The last DRDTeam devbuild before that is at 01b5c5e44.

**Comment by Altazimuth** [comment]
OK the rendering error is introduced by b0888fae1f60f03f2054d1e002bf46f7729190df. It appears present when you view the slopes for a different portal layer. I can't repro a crash but, yeah.

**Comment by Meerschweinmann** [comment]
Hooray, the new fix works flawless in my first posted map and the here uploaded test-map. Thanks you.

The crashes happened in total two or three times on both maps i tested. It seemed turning around the DOOM guy, near the slope in the above Portal sector flying, to view the glitching slope does the crash

Getting the slope glitching from distance and then flying to it did not crash. It seemed to me that it happened when the whole glitching slope came instantly and nearly flying on screen by turning the flying DOOM guy.
But i don't get it how to surely reproduce.

I had tested the glitching slopes many times, so two or three crashes were not the majority behavior.
