### ISSUE TITLE
EDF animations which start with a random-duration pic no longer work

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#628]
Got this notice from a user:

> just to notice, in August devbuilds if a wall animation defined in de SWITCHES/ANIMATION lump starts with a pic with random tics it doesn't work. I just overcome this putting the first frame with normal static duration and the rest can be random or static .

Need to check.

**Comment by Altazimuth** [comment]
After receiving clarification, it's EDF animations, not ANIMATED/SWITCHES.

```
animation
{
  wall ANIWAL
  pic {name ANIWAL1 random 35,42}
  pic {name ANIWAL2 random 35,42}
  pic {name ANIWAL3 random 35,42}
}
```
The above block used to work but no longer does, whereas:
```
{
  wall ANIWAL
  pic {name ANIWAL1 tics 7}
  pic {name ANIWAL1 random 35,42}
  pic {name ANIWAL2 random 35,42}
  pic {name ANIWAL3 random 35,42}
}
```
works appropriately.

**Comment by ioan-chera** [comment]
Regression came with https://github.com/team-eternity/eternity/pull/615; I've fixed that by correcting the reset to be exactly like when starting Eternity. Fixed.
