### ISSUE TITLE
Widescreen intermission screens showing in 4:3 aspect ratio while wiped or faded away.

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#629]
Good morning.

As i have tested out because i made 32:9 assets for DOOM, EE can show 32:9 (854 pixel wide) widescreen assets.

One thing i have noticed ist, when EE shows the intermission screens, before entering the next level, while the intermission screen is wiped or faded away, a 4:3 frame shows up and cuts the extended areas of the widescreen assets.

That can be seen too when using the new DOOM + DOOM2 release WADs with its integrated 16:9 assets.

**Comment by Meerschweinmann** [comment]
That 4:3 showing while wipe behavior does not occur with the titlescreen.

**Comment by ioan-chera** [comment]
It doesn't look to be caused by the wipe transition, as it also happens without it. Something seems to cut off the margins of the widescreen display at the end of the intermission.

**Comment by ioan-chera** [comment]
Fixed, it was refreshed by default to pillarbox.

**Comment by Meerschweinmann** [comment]
Super. Thank you. The next stable EE release will have many new features and the best EE we ever had 💪😃
