### ISSUE TITLE
Instant crash idclevving to modded map

### ISSUE THREAD

**Issue by GastonLahaut** [team-eternity/eternity#630]
Last working build: 1361. Anything more recent will instantly crash when using idclev to warp to a modded level.
[CRASHLOG(1).TXT](https://github.com/user-attachments/files/16754190/CRASHLOG.1.TXT)

Idclev to vanilla map works; taking the normal exit to this modded map (map04) works; icclevving from modded map back to map01 works; idclevving to modded map (after having visited it already) also works. But after starting in map01 and idclev to modded map 4: crash. Tried with a different modded map (map05): no issue

**Comment by ioan-chera** [comment]
hmm
```
Backtrace:
00000001401053ef P_CheckSectorPortalState
0000000140128725 P_SetPortal
00000001401295bd P_SpawnPortal
0000000140129f34 P_SpawnSpecials
```

**Comment by ioan-chera** [comment]
Made a commit now, please re-check.

**Comment by GastonLahaut** [comment]
Rebuild of previous troublesome map with minor texture changes made the issue go away? Perhaps this is dependent on memory layout..? New build 1372 also tested without issue,  Suggest keeping this open for a while longer, to see if this issue pops up again.

**Comment by ioan-chera** [comment]
Closing due to staleness
