### ISSUE TITLE
DOOM2, Plutonia and TNT BOSSBACK shows in 4:3 frame with widescreen assets

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#631]
Hello.

I was a bit hasty with saying widescreen assets work flawlessly :)

DOOM2, Plutonia and TNT BOSSBACK are shown in a 4:3 frame. You can see it even with the official Kex WAD.

**Comment by ioan-chera** [comment]
Fixed both for the cast finale and for custom endpic mapinfo settings to work with widescreen assets.

**Comment by Meerschweinmann** [comment]
Hey, that was very fast. Thank you :) Have tested it with the 32:9 assets now and they worked fine.
