### ISSUE TITLE
Doom 64 for Doom II map 17 crashes when sky should change in latest dev build

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#633]
Hello.

User Jesion from Doomworld has found an issue with D64D2.WAD and the latest EE dev-build.
Link to the Doomworld-post:
https://www.doomworld.com/forum/topic/147828-eternity-devbuild-crashes-when-changing-skies/

I can confirm that too.

Map 17 of this map has a sky that changes everytime a thunder-sound plays.
The EE Forseti release has no problems.

Unfortunately the latest DRD-dev-build crashes with:

R_RunContexts: Error in context(s):
        1: R_GetSkyTexture: Failed to get sky texture for texturenum 456
        2: R_GetSkyTexture: Failed to get sky texture for texturenum 456
        3: R_GetSkyTexture: Failed to get sky texture for texturenum 456
        4: R_GetSkyTexture: Failed to get sky texture for texturenum 456

The problem can be seen directly from the start of map 17. 
When walking around in the start area after some time the thunder should come and the sky changes.

The WAD can be found here:
https://www.doomworld.com/idgames/levels/doom2/megawads/d64d2

Greetings

**Comment by Meerschweinmann** [comment]
The oldest DRD dev-build from August 14. that i could download has the problem already.

**Comment by Altazimuth** [comment]
Fixed by 3ee9811490da85d6b08342ed692062dc83d2e9fe.

**Comment by Meerschweinmann** [comment]
Thank you 😃
