### ISSUE TITLE
(zdoom-hexen-specials) Unify the EV_ procedures

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#64]
There are similar/duplicate actions between EV_DoStuff and EV_DoParamStuff. EV_DoStuff should really flow into EV_DoParamStuff which will be the only one setting up the thinker or other map action. After that, try to remove the redundant kinds and types of input parameters and thinkers. This will make a Doom->UDMF conversion clearer.

This goes without saying: demo regression testing is most important here.

**Comment by haleyjd** [comment]
No this separation is for simplicity and compatibility assurance. I will not consider this.
