### ISSUE TITLE
When using no Widescreen assets, the default 4:3 assets have a thin garbage-pixel line on the left side.

### ISSUE THREAD

**Issue by Meerschweinmann** [team-eternity/eternity#640]
Hello.

That is nothing that really bothers me because i am using widescreen assets and most people should not notice or pay attention to it, but just for info for the case you did not know it.

When using no Widescreen assets, the default 4:3 assets have a thin garbage-pixel line on the left side.

![etrn26](https://github.com/user-attachments/assets/7a6027ce-642f-4dcf-8a48-08788a3b8a4c)

**Comment by Meerschweinmann** [comment]
Seems to be an only with some 1600 lines resolution "problem".

I get that garbage line with the native resolution of my notebook (2560x1600) and with 3840x1600 pixels on my desktop.

A resolution of 5688x1600 and every other resolution i had tested is fine.

But as mentioned before. I have to use no widescreen assets to see it, which was only because i set up a new fresh folder with EE and had no ws assets in it.

**Comment by ioan-chera** [comment]
The trace on the left is just a retention of the previous image (would be HOM on double-buffered renderers)! It seems that the pillarbox doesn't end up exactly where the picture starts. Need to find out why the off-by-one error happens.

**Comment by Meerschweinmann** [comment]
Can confirm that the garbage line has gone on my laptop with latest self compiled dev-build.
Good for those without widescreen assets and widescreen monitors 👍

Just for the case you can influence that, the last DRD dev-builds have a size of 0 bytes and so they do not work.
