### ISSUE TITLE
Version in the title bar is separate from CMake or version.cpp

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#646]
We missed it and need to update it.

- [x] Either document it internally or make it dependent on CMake or version.cpp

**Comment by Meerschweinmann** [comment]
Hello.

Here is the wrong version mentioned too. Or is this the so called title bar?

![EE_Crash_Version](https://github.com/user-attachments/assets/750e33b4-552f-4126-a301-3d68b614856a)

**Comment by FozzeY** [comment]
Looks like a separate string in version.cpp https://github.com/team-eternity/eternity/blob/master/source/version.cpp#L43

**Comment by ioan-chera** [comment]
Oh... OK, guess I didn't pay enough attention!
