### ISSUE TITLE
Unable to quit game by pressing Y if the keyboard input language is non-English

### ISSUE THREAD

**Issue by deviant27** [team-eternity/eternity#658]
Hello, there is a problem with the port which is described in the title. Since I have Russian keyboard language ON most of the time, I always have to either press Enter in order to quit the game or to switch the keyboard language which is a bit uncomfortable. Don't know if it happens with the other non-English lettered languages (for example, Chinese), but it may be so. Thank you!

**Comment by ioan-chera** [comment]
As a workaround, try if the [enter] key (or whichever key you have bound to choose the current menu item) works the same as "y" when you're about to quit.

It would be interesting to see how Eternity handles internationalization, but that would require adding a lot to the bitmap Doom font. I wonder if we have any unicode Doom fonts in the community, preferably under the same style as the main Doom font.

**Comment by ioan-chera** [comment]
Fixed by using the scan code as an alternative.
