### ISSUE TITLE
Multithreaded rendering sprites cut off

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#665]
Happens with Eviternity 2 MAP14 with multithreaded rendering, even by having thorough rendering, very wide sprites can get cut off:

Good: 
![image](https://github.com/user-attachments/assets/c2982c3f-d309-4f90-a615-6118705932d7)

Bad: 
![image](https://github.com/user-attachments/assets/907ebdbc-9840-4b82-9218-86506f96e69e)

Need to figure out if fixable.

**Comment by Altazimuth** [comment]
I've talked to you about this. I've told you how it's fixable.

**Comment by Altazimuth** [comment]
Also Rum and Raisin fixes this too, though I think in a different way than I had planned. Its methodology is probably better than mine so it's likely worth asking GooberMan.

**Comment by ioan-chera** [comment]
> I've talked to you about this. I've told you how it's fixable.

Can you please re-post?

**Comment by Altazimuth** [comment]
>I basically need to do what you did with the cross-portal sprite projection in terms of getting sprite width, but then use the same method to insert it into blockmap style per-sector sprite-touching lists.
And then use those lists in rendering instead of the blockmap ones.
Or use whatever approach GooberMan cooked up for R&R.

It's worth looking into what GooberMan did for R&R as I think that approach is multithreaded and likely faster. No idea if EE can use it without issues (given portal exist) but it's definitely worth researching.

**Comment by ioan-chera** [comment]
Is the problem the fact that we're using `touching_thinglist` to scan surrounding sectors? That list only checks what sectors the thing is physically touching with its radius. We'd need to make yet another list for the touching by sprite size, and that'll need to be updated on every graphical change, including scaling… not easy.
