### ISSUE TITLE
Eternity does not load the correct Freedoom IWAD files with -iwad

### ISSUE THREAD

**Issue by chungy** [team-eternity/eternity#7]
This is some strange behavior. With `-iwad freedoom2.wad`, Eternity loads freedm.wad instead.  With `-iwad freedm.wad`, it claims the IWAD cannot be found at all.  Only `-iwad freedoom1.wad` seems to work properly.

Specifying the absolute path to the files works, however, such as `-iwad /usr/share/games/doom/freedoom2.wad` and `-iwad /usr/share/games/doom/freedm.wad`.

Running on 64-bit Arch Linux

**Comment by haleyjd** [comment]
Was this a fresh config or one hung over from after the project changed all the IWAD names?

**Comment by chungy** [comment]
This is still the behavior with a fresh config.

**Comment by Altazimuth** [comment]
I found the source of the bug, which is here: https://github.com/team-eternity/eternity/blob/cac98ed89a9cb1161337849f84bcf9479ddf15ff/source/d_iwad.cpp#L853-L854
The issue is that it doesn't check for the FREEDM lump. I have a fix ready, and just need to consult Quasar before moving forward.
