### ISSUE TITLE
Dedicated jump sound

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#72]
Legacy and ZDoom have had this for years, using DSJUMP as the standard name. Would be nice if Eternity followed this too.

**Comment by sneakernets** [comment]
In terms of Legacy skin support, this is pretty much a given. Was probably an oversight because, believe it or not, there was once heated debates on whether the doomguy should jump. That being said, EE now has it, we need to add a sound capability for it.

**Comment by ioan-chera** [comment]
done
