### ISSUE TITLE
Particles do not traverse portals

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#77]
As the title says.

**Comment by sneakernets** [comment]
Particles aren't actual things in the game world, unfortunately, and independent from the game code. This is to enable particles to be displayed in demos without desyncs.

**Comment by ioan-chera** [comment]
Yeah i know, i was too lazy to fix it. Particles are so 1999. ZDoom fixed it, i believe.


Trimis de pe Samsung Mobile

<div>-------- Mesaj original --------</div><div>De la: sneakernets <notifications@github.com> </div><div>Date:30.03.2016  18:41  (GMT+02:00) </div><div>Către: team-eternity/eternity <eternity@noreply.github.com> </div><div>Subiect: Re: [team-eternity/eternity] Particles do not traverse portals (#77) </div><div>
</div>Particles aren't actual things in the game world, unfortunately, and independent from the game code. This is to enable particles to be displayed in demos without desyncs.

**Comment by ioan-chera** [comment]
Fixed!
