### ISSUE TITLE
Sprite culling through portals is still iffy

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#80]
Despite being in front of this sector, the ground is overlapping the character for some reason.

http://i.imgur.com/T5W2iFh.png

**Comment by ioan-chera** [comment]
Can you show a cheated automap view of the things, preferably with MS Paint annotations on the actual things and portals? Are you using line portals and/or sector portals?

**Comment by ioan-chera** [comment]
@Blastfrog I need proof that this happens, in form of a test wad.

**Comment by ioan-chera** [comment]
Closed. I'll open another issue if i find one of my cases.
