### ISSUE TITLE
Some walls not rendering in full when seen through portals

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#81]
Look just above the crosshair in this image.

http://i.imgur.com/2JfpXos.png

**Comment by ioan-chera** [comment]
What kind of portal am I looking at here? A sector portal with the plane at the same level as the edges? Does this still happen?

**Comment by ioan-chera** [comment]
I need a test wad with this reproduced.

**Comment by ioan-chera** [comment]
@Blastfrog  I need a wad with this happening.

**Comment by ioan-chera** [comment]
Closed. May be fixed for all I know.
