### ISSUE TITLE
Sky distorted in FOVs other than default

### ISSUE THREAD

**Issue by Blastfrog** [team-eternity/eternity#84]
The sky scales correctly horizontally, but does not adjust at all vertically. It works fine for the default FOV in any given aspect ratio, but non-standard FOVs are an issue.

**Comment by ioan-chera** [comment]
I need more info on what you're trying to do. If you changed some display settings and got this effect, then please provide the steps. If you modified the source code of Eternity to get this bug, then it's out of my scope to fix.

**Comment by ioan-chera** [comment]
Closed because it's unclear.
