### ISSUE TITLE
Player view height issue in MAP20 of Ancient Aliens (RC3a)

### ISSUE THREAD

**Issue by devinacker** [team-eternity/eternity#85]
Playing MAP20 of aaliens_rc3a.wad in the latest revision causes the player's view height to rapidly shift up and down, seeming to alternate between floor height and normal every few tics. No other maps seem to have the issue, and the 3.40.46 release itself isn't affected.

**Comment by chungy** [comment]
Looks like 256f07a48bd36825ee7bdd3f60a46628d1ee50c1 introduced this problem.

**Comment by haleyjd** [comment]
This is precisely why I don't refactor by combining code, unless I am 100% certain that all variations are accounted for.

**Comment by Altazimuth** [comment]
I figured out the problem. What happens is that the map uses Boom conveyors for scripting, and certain scripts are on a loop. P_dropToFloor is called on teleporting, and my guess is that it quickly sets you to the level of the voodoo doll, and the sanity check puts you back up again. See the setup for the teleport and the offending function call respectively.
http://i.imgur.com/THAGIwt.png
https://github.com/team-eternity/eternity/blob/master/source/p_telept.cpp#L85

**Comment by devinacker** [comment]
I took a look at the diff last night and had the same suspicion, but it was kind of puzzling since it didn't seem like P_Teleport was doing anything functionally different than before. There's probably some weird niggling detail about the refactor that I missed, though.

**Comment by haleyjd** [comment]
The function created to do the shared viewheight adjustment logic is getting around the check against voodoo dolls by re-pulling the player_t * from thing->player; this is inappropriate. It needs to take player_t *player as an additional argument from the calling function so that it will be NULL if the thing is a voodoo doll.

**Comment by haleyjd** [comment]
Should be fixed, please confirm if you're able.
