### ISSUE TITLE
Non-solid slopes don't clip sprites

### ISSUE THREAD

**Issue by Altazimuth** [team-eternity/eternity#99]
The left eye can be seen through the non-solid slope, but the right one can't be seen through the solid slope. This might be a side-effect of not clipping anything at all, but if that's the case then I'm not sure why solid slopes are fine.
![etrn13](https://cloud.githubusercontent.com/assets/5298767/17894733/505231ca-6942-11e6-817d-595944bc9988.png)
![etrn14](https://cloud.githubusercontent.com/assets/5298767/17894731/504a0766-6942-11e6-94e2-20df5855f163.png)
![etrn15](https://cloud.githubusercontent.com/assets/5298767/17894732/504cba56-6942-11e6-9680-e7efe9c36002.png)

**Comment by ioan-chera** [comment]
Postponed for the slopes epic. It requires some advanced slope physics calculations.

**Comment by ioan-chera** [comment]
The problem is in R_StoreWallRange: there's a thing called "silhouette" which assumes non-sloped sectors.

**Comment by ioan-chera** [comment]
fixed
